### ISSUE TITLE
AccountHeader + !selectionListEnabled = unexpected paddingRight

### ISSUE THREAD

**Issue by dstd** [mikepenz/MaterialDrawer#1007]
Hello Mike!

When `mSelectionListEnabled == true` in AccountHeader it looks fine. But when it's disabled, the account name is clipped on a halfway.
Is there some way to reduce the right padding when `.withSelectionListEnabled(false)` is used?

Here some pictures of what I mean:
№1 - it's clear why the margin is here
№2 - looks like right-padding should be reduced
![drawer](https://cloud.githubusercontent.com/assets/1444844/13060052/af60f612-d43f-11e5-84de-728cfc471bdf.jpg)

**Comment by mikepenz** [comment]
@dstd because of the way the layout is set up, and the RTL support it features, i can't change this for the included layout. 

If you do not need the arrow in your application you could modify the layout for your case and overwrite the original one. 

Copy the original layout into your application, change the layout to your needs (keep the name) and afterwards it will automatically use your modified version (keep in mind you can not delete the view as it is still called inside the code)

Thanks

**Comment by dstd** [comment]
Thank you for the advice!
