### ISSUE TITLE
Save selected item inside expandable item and do not select expandable item root

### ISSUE THREAD

**Issue by westman2000** [mikepenz/MaterialDrawer#1026]
1. Please, save selected item position inside expandable item. For example, when i expand item, than select item inside, and than collapse item again, selection position do not save position.

2. If drawer has only expandable items, on first start first item(expandable item) in drawer always shown as selected, even if i set withSelectable(false) on this item

**Comment by mikepenz** [comment]
@westman2000 
1.) if you collapse an item, the `FastAdapter` can't keep the selection for the items which are in the sub group. In this scenario you will have to remember that selection on your side. The `FastAdapter` can only remember selections for existing items. Otherwise this would also cause problems when restoring the sate upon activity re-creation. 
2.) you can completely disable the default selection of the first element as shown here:
https://github.com/mikepenz/MaterialDrawer#how-can-i-create-a-drawer-without-a-default-selection
