### ISSUE TITLE
Header section on click listener doesn't close the drawer on returning false

### ISSUE THREAD

**Issue by kayvannj** [mikepenz/MaterialDrawer#1065]
```java
mAccountHeader = new AccountHeaderBuilder().withActivity(this)
        .withTranslucentStatusBar(true)
        .addProfiles(profile)
        .withHeaderBackground(R.drawable.drawer_header_bg)
        .withSelectionListEnabledForSingleProfile(false)
        .withAlternativeProfileHeaderSwitching(false)
        .withOnAccountHeaderSelectionViewClickListener(new AccountHeader.OnAccountHeaderSelectionViewClickListener() {
            @Override public boolean onClick(View view, IProfile profile) {

                ...

                //false if you have not consumed the event and it should close the drawer
                return false;
            }
        })
        .withSavedInstance(savedInstanceState)
        .build();
```

**Comment by mikepenz** [comment]
@kayvannj you might mix up things here. 

The `OnAccountHeaderSelectionViewClickListener` is used to notify you about the click on the toggle. If you return `true` here you can prevent the toggling to the profile list. This event is not meant to close the drawer. 
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeaderBuilder.java#L1323
This just happens when you select a profile itself. 

(you can still do `mDrawer.closeDrawer()` in here if you need to)

**Comment by kayvannj** [comment]
I see, thanks.
