### ISSUE TITLE
How change drawer item selector?

### ISSUE THREAD

**Issue by egisxxx** [mikepenz/MaterialDrawer#108]
Hello,
i'm using this library in own project. It is very best navigation's library. Thanks.
my project using minSdk > 10 :( 
1) Several hours i tried to find approach on old android (2.3 version), how i can change navigation drawer item's selector. (orange color will appear, when pres item) to be clear about what, added screenshot. 
![old_android](https://cloud.githubusercontent.com/assets/6225633/6657130/8309c61a-cb4a-11e4-9a28-6a86266ee995.png)
2) when navigation item is selected, isn't showing selected element in navigation drawer (on Android 2.3 version, newest - ok)

**Comment by mikepenz** [comment]
@egisxxx seems to be an issue with API Level 10 (the default list-item selector must overlap the item. strange) this can't be changed by code. Only if you would create your custom drawerItem implementation. Will have to take a closer look at it :/

API level 10 was not yet able to show the selected state. this is an issue i know, but i have not found a solution for this issue. I have the feeling this won't come to the MaterialDrawer because this would require a lot of additional stuff just to get it working with API Level 10

**Comment by mikepenz** [comment]
if you find an easy solution for the second issue let me know or create a pull request. thanks.

**Comment by mikepenz** [comment]
@egisxxx i just found out a easy solution how you can change the listitem selector. just get the ListView from the Drawer.Result and overwrite the selector there.

Also i've fixed the overlapping on click feedback with the next version
