### ISSUE TITLE
ExpandableDrawerItem - subitem selection lost on collapse / expand

### ISSUE THREAD

**Issue by fliespl** [mikepenz/MaterialDrawer#1109]
As mentioned in the title - subitem selection is lost on collapse / expand.

**Comment by mikepenz** [comment]
@fliespl that's the correct behavior. If you want to reselect you should remember the selection of the sub item and set it again when expanding the item. 

This behavior is because the `FastAdapter` always keeps track of the items and the selections to be performant, and it can't keep the selection of an item which is not part of the current `Adapter` (a sub item is removed when the parent gets collapsed)
