### ISSUE TITLE
Translucent status bar with multiple drawers

### ISSUE THREAD

**Issue by kakai248** [mikepenz/MaterialDrawer#1113]
I have a left drawer and a right drawer. I want the left one to be drawn over the status bar and the right drawer under. I can't seem to get this behavior. I either get both to be drawn over or both under. This was working in version 4.6.4 and it's not in current version.

**Comment by christianguevara** [comment]
Calm down, this is not a place where you can request things...
Is not "i want" is maybe "can you help me ?"

**Comment by mikepenz** [comment]
@kakai248 as of v5.0.0 and upwards the **MaterialDrawer** depends on the `fitsSystemWindows` flag to manage the `paddings` and shadow behind the `StatusBar` everything is now handled by the system. 

If this is possible with a normal `DrawerLayout` and the flags it is also possible with the `MaterialDrawer`. 

More or less this was a good side effect of the previous implementation as paddings were managed manually (it required the fullscreen flag which had other side effects).
I think the only way how you could get this working is to use 2 `DrawerLayouts` where one is `fitsSystemWindows=true` and the other one `fitsSystemWindows=false` (which will prevent any `CollapsingToolbar` behaviors etc. Content won't be possible to go behind the `StatusBar`)
I highly recommend that you don't do this because this will add another view layer, and might cause lower performance. 

@christianguevara thanks. ;)

**Comment by kakai248** [comment]
I'm sorry if I sound demanding, it was not my intention at all. I expressed myself incorrectly, I only want some guidance.

@mikepenz I was trying to follow [https://www.google.com/design/spec/layout/structure.html#structure-ui-regions](this), where the right nav is under the status bar. How would Google go about doing that with a single ```DrawerLayout```? It's merely a design issue, for which I don't want to overcomplicate. So you're saying it's not worth it?

**Comment by mikepenz** [comment]
@kakai248 everything is fine. Don't worry. 

To be honest I do not know about a google app having a two sided drawer. I know about this guideline. But if the default `DrawerLayout` from Google` does not generate it automatically like this, I guesst the only other solution is to go with 2 `DrawerLayout`s which is in my assumption a bit to overcomplicated. Perhaps someone else has a better solution how to get this done. 

Otherwhise if everything is fine, you can just stay with the pre v5.x.x version of the drawer.
