### ISSUE TITLE
Wrong icon colors on certain Apis and/or devices

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#1160]
As discussed in #1152 

I could reproduce it with a Nexus 5 Api 23 Emulator and my physical OnePlus 2 with 6.0.1.
This is how I declare an item:

```java
new PrimaryDrawerItem().withName(R.string.drawer_item_news)
                .withIcon(CommunityMaterial.Icon.cmd_newspaper)
                .withSelectedTextColorRes(R.color.primary).withSelectedIconColorRes(R.color.primary)
                .withIconTintingEnabled(true).withBadgeStyle(new BadgeStyle()
                        .withColorRes(R.color.primary).withTextColorRes(android.R.color.white))
                .withIdentifier(DRAWER_ID_NEWS)
```

**Comment by rubengees** [comment]
If you need any info that could be helpfull, feel free to ask.

**Comment by rubengees** [comment]
Ah I forgot to mention: This Bug seems to got introduced in one of the last releases. It worked fine until like 2 releases on my device.

**Comment by mikepenz** [comment]
@rubengees just a quick thought. Your issue might be related to the fact that you enable `tinting` for the `IconicsDrawable` which already get colored automatically without the need for thinting

**Comment by mikepenz** [comment]
@rubengees ok. The issue is really related to the `tinting` enabled for an `IconicsDrawable` just remove it, and it works fine. 

A bit more detailed description:
The `IconicsDrawable` is already created with the correct color, and transparency. If we now enable tinting for those icons too, we will get in the bad case that we have double the transparency applied via the tinting, which results in a brighter item. 

So
```java
new PrimaryDrawerItem().withName(R.string.drawer_item_news)
                .withIcon(CommunityMaterial.Icon.cmd_newspaper)
                .withSelectedTextColorRes(R.color.primary).withSelectedIconColorRes(R.color.primary)
                .withBadgeStyle(new BadgeStyle()
                        .withColorRes(R.color.primary).withTextColorRes(android.R.color.white))
                .withIdentifier(DRAWER_ID_NEWS)
```
will result in the correct color

**Comment by rubengees** [comment]
Ah great, works! Thanks once again for your help!
Weird though that this is only reproducable on some devices...
Just because I'm interested, why is that?

**Comment by mikepenz** [comment]
@rubengees it's more related to the API version rather than the devices. The problem is that there seems to be an issue (or might be just sdk limitation) which handles transparencies a bit different on `StateListDrawables`. On new api's it does not apply the transparency twice, but this happens on older versions. 
It even goes a leel below this. As this issue exists I had to implement a custom `StateListDrawable` which allows the older APIs to properly display the icons. --> my `PressedEffectStateListDrawable` this is required to properly allow the icons to show the correct color over the different states. 

This is only necessary because I support APi versions below 19. You wouldn't believe how many custom things are in the drawer, just to provide compatiblity with all devices, manifactures, and down to API 10...

**Comment by rubengees** [comment]
Ah the struggle with Android... :D
Yes I know what you mean, I also always have a package in my projects just with bugfixing and compability classes.
Thanks for the insight!
