### ISSUE TITLE
strange behavior of a customized Drawer Item

### ISSUE THREAD

**Issue by soheilserver** [mikepenz/MaterialDrawer#1227]
I have made my own Item Drawer which extends BaseDrawerItem. this customized item has a specific number of Radio Buttons and the number of them is specified in the app. I add these Radio Buttons to a Linear Layout which is a part of my Item Drawer's layout. this process happens in bindView method.
the problem is that when I add one of these Items to drawer, then remove it by calling removeAllItems() and then add a new object of these items with a new number of Radio Buttons, what i see is a mixture of the previous item and the new item! I mean the previous radio buttons are at the first and the new radio buttons after them!
I had override the method getType at this way:
`    @Override
    public String getType()
    {
        return "RADIO";
    }`
then I changed that to
`    @Override
    public String getType()
    {
        return String.valueOf(getIdentifier());
    }`
and the problem disappered! but I can not get what was exactly the problem and why got solved at this way?
thank you so much

**Comment by mikepenz** [comment]
@soheilserver the type should be a fixed value. So "RADIO" was fine. 

I am not quite sure what you do with `removeAllItems()` and so on. 
You might provide some details about your implementation. (code :D)

What you always have to keep in mind. Items are reused by the `Adapter` so you have to make sure in the `bindView()` method everything is done to get the item you need, you can not depend on the view you get. because it may has data set from the previous item which used this items view. 

--> That's how a RecyclerView works. It reuses views based on the `type` we define. (The drawer works a bit more generic thanks to the `FastAdapter` so you don't have to write the `Adapter` logic you normally would have to write if you go the normal route via a RV)

**Comment by soheilserver** [comment]
> you have to make sure in the bindView() method everything is done to get the item you need, you can not depend on the view you get
thank u so much. your explanation helped to get rid of the problem.
but there is still another problem! when I click on my customized item, bindview gets called again, however I havn't set any onClickListener for my item. why does it happen and how to prevent?
thanxs dude ;)

**Comment by mikepenz** [comment]
@soheilserver there are 2 possibilities how the `FastAdapter` can be configured. Either it will use the normal `setActivated()` method on the view and will Android allow to handle everything via the view states, or the setting which will cause a `notifyItemChanged` on the `Adapter`

By default it uses the `setActivated()` way: 
https://github.com/sathishmscict/FastAdapter/blob/master/library/src/main/java/com/mikepenz/fastadapter/FastAdapter.java#L45

So the only thing I could think of here is that you changed this configuration on the `FastAdapter` (`Drawer.getAdapter().withSelectWithItemUpdate(true)`)

Otherwise it may be related to your layout or something like this which I can not prevent or change on the side of the `FastAdapter`
