### ISSUE TITLE
Find an SecondaryDrawerItem's ID 

### ISSUE THREAD

**Issue by Arathus** [mikepenz/MaterialDrawer#1229]
Hello! 

Big respect for the nice library! ;)

But I need to find a SecondaryDrawerItem's ID, I can't do it...

I'm using an another library, what needs the ID of the last item of my drawer. 
If it is not possible, it is also good to get the view of the last SecondaryDrawerItem.

Is it somehow possible ?

**Comment by mikepenz** [comment]
@Arathus you want to search a `SecondaryDrawerItem` by it's id or you have the `SecondaryDrawerItem` and want to get the id?


Because there is the method `getIdentifier()`
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/AbstractDrawerItem.java#L47

**Comment by Arathus** [comment]
I want to get the SecondaryDrawerItem's ID.
I saw the getIdentifier() method that before, but it not worked me...

lenyilo is a Drawer...

 Target viewTarget = new ViewTarget(lenyilo.getDrawerItems().get(8).getIdentifier(),a);

"the first parameter here must be the ID of the view what I want to highlite , and the second is the activity"

"I also can give to this function just one parameter (the view)"


                    ShowcaseView sv = new ShowcaseView.Builder(a)
                            .setTarget(viewTarget)
                            .setContentTitle("ShowcaseView")
                            .setContentText("This is highlighting the Home button")
                            .setStyle(R.style.MaterialTutorialTheme)
                            .withMaterialShowcase()
                            .setShowcaseEventListener(el)
                            .replaceEndButton(R.layout.tutorial_button)
                            .build();
                    sv.setButtonPosition(lps);

But in this way the program produce 


> Could not find class 'com.mikepenz.materialdrawer.view.BezelImageView$CustomOutline', referenced from method com.mikepenz.materialdrawer.view.BezelImageView.onSizeChanged
> 04-28 19:00:45.272  26701-26701/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
>     java.lang.NullPointerException


Have you any idea what is the problem ? How should I solve it ?

**Comment by mikepenz** [comment]
@Arathus ah I see your issue. You missuse the `Identifier` of the  `DrawerItems` as the `views` `identifier` which is a different one. 

The issue is that there is no unique identifier which you can use, as there may be more than one `SecondaryDrawerItem`s in your current drawer, so the identifier can't be used. The view also can't be used as this one is not known by the item, as views are reused inside the `RecyclerView` which is used inside the `Drawer` 

The only thing which might work is that you get the `RecyclerView` from the `Drawer` and get the `View` from a specific position within the `RecyclerView` but note that this might also fail if the user was to fast and scrolled before the intro screen was shown. 

But retrieving a view from a position in a `RecyclerView` is then not related to this library

**Comment by Arathus** [comment]
I can't find the way how can I get the `RecyclerView` from the Drawer...
Have you thought to the `getAdapter` method, or to the `getListView` mehod ?
I'm a junior programmer, so I have to learn more :)

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L214

**Comment by mikepenz** [comment]
As mentioned this is a complex behavior as the items are in a `RecyclerView` so no static content as it would normally be for a intro activity

**Comment by Arathus** [comment]
I had an earlier version of your library ;D
Excuse me about that ;)
I will try what you said

**Comment by mikepenz** [comment]
@Arathus things changed a lot since the version where the drawer used a `ListView` 
I switched to `RecyclerView`  starting with v4.0.0 

https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md
