### ISSUE TITLE
make changes into material_drawer_item_profile.xml

### ISSUE THREAD

**Issue by alex-soft-r** [mikepenz/MaterialDrawer#130]
can u add to future releases some changes into "material_drawer_item_profile.xml"
    <LinearLayout
       ...
        android:gravity="center_vertical">
this will allow show name or email (or booth) at vertical center of layout :)

**Comment by mikepenz** [comment]
@alex-soft-r with the setting `setNameShown()` you can hide the name of those items and then the e-mail will be centered. Can't try it right now if i'm correct but yeah. only adding center_vertical won't change how the items are displayed because with empty text the textView itself is still displayed just without content.

**Comment by mikepenz** [comment]
@alex-soft-r oh i see your point. totally missed this with yesterdays update. sorry. will be fixed in v2.5.5
