### ISSUE TITLE
Updating subItem without having the parentItem collapsing

### ISSUE THREAD

**Issue by BobOtike** [mikepenz/MaterialDrawer#1371]
I have multiple ExpandableDrawerItems with multiple subItems each. Whenever I update one of the subItems, the respective parentItem collapses. Is there a way to update the content while retaining the expanded state of the parent?

**Comment by mikepenz** [comment]
https://github.com/mikepenz/MaterialDrawer/issues/1260#issuecomment-218735178

**Comment by BobOtike** [comment]
Okay, seems that I have misinterpreted the reason for the closing. Updating the parent causes it, even if using notifyAdapterItemChanged() since that calls through to notifyAdapterItemRangeChange(), which always closes the item if it is expanded. Is there any way to prevent that?

**Comment by mikepenz** [comment]
@BobOtike if you update just a sub item (so not a normal item) you should call:
```java
notifyAdapterSubItemsChanged
```

There is no way to prevent the closing with the other `notifyAdapterItemChanged` method as it otherwise would not be able to correclty udpate the item

**Comment by BobOtike** [comment]
Thanks for your response. The thing is, I want to both update the parent and one of its subItems at the same time. 
I see that the expanded state is properly being restored since my isExpanded() will still return true after the update, but because of the ItemAnimator this leads to a consecutive fading out and in of the subItem, which is not really desirable as it looks like the item is blinking. One way to prevent that is of course to set the animator to null, but than I lose all the fancy animations which is also not desirable. Everything I've tried to prevent that blinking like setting the animator to null before the update and reinstating it afterwards also failed. Any idea how to overcome this?

**Comment by mikepenz** [comment]
You may can check the following:
https://github.com/mikepenz/MaterialDrawer/issues/1017#issue-134587256

the animation plays automatically via the `notifyItemChanged` event which I have to provide to the `RecyclerView` so it will redraw the element with the new information

**Comment by BobOtike** [comment]
Activating stableIds, which is was providing before anyways, seems to have fixed the blinking issue. 

Thanks a lot for your quick responses, cheers mate!

**Comment by mikepenz** [comment]
@BobOtike yeah stableIds is quite useful. Just make sure all your items have ids. By default (I think) there are id'S given to all items in the drawer

**Comment by BobOtike** [comment]
It appears so. While the blinking of the subItem was gone just because of stableIds, I still had some blinking of the parent's name/description when only switching its icon. In this case I now use the approach suggested in your last link and update the view myself without involving the adapter, and at first glance it works like a charme.

**Comment by NoHarmDan** [comment]
After reading through several issues, I still fail to understand how collapsing/expanding and the ExpandableExtension work. I was forced to update an ancient app to the newest appcompat version of MaterialDrawer (6.0.9 from 5.5) due to Google's API 28 requirements and inherent compatibility issues.

The menu in the app has several primary items that each have several sub items. The required (and previously working) behavior is that all items are expanded by default and stay so unless the user manually collapses them. Regardless of any changes to them. They do undergo changes regularly: the label, the badge and the icon can all change. The badge changes very often to reflect to state of the item, where it's very undesirable for the item to suddenly become invisible because its parent collapses.

Now you suggest calling the `notifyAdapterSubItemsChanged(int globalPosition)`, which isn't available anymore, as it now also requires the number of previous sub items - not a problem really I guess. Problem is, I fail to understand when exactly I should call this, because so far it has only thrown a `ConcurrentModificationException` with a useless stacktrace.

To clarify what I'm trying to do in the case of say updating the icon:
-  Something is rendered into a `Drawable` and `item.withIcon(drawable)` is called on the respective `SecondaryDrawerItem`. Previously what I would do next was to call `drawer.updateItem(item)`, which still works, but it might be (not 100% positive this is the cause) collapsing **ALL** the expandable items in the menu.

And the badge:
- `updateBadge(identifier, badge)` is called and again, **ALL** expandable items are collapsed.

Pretty much the same goes for the title, but that changes rarely. In none of the cases any of the `notifySomethingChanged` methods have ever been explicitly called (I presume the `updateBadge` or `updateItem` methods do call that somewhere deep inside) and everything work perfectly until the update.

I'm not really sure updating the sub items is the reason why **all** collapsible items (including those whose items are never updated) seem to be collapsed every time the menu is opened, regardless of the state they were left in, but it appears to be the most probable cause. Meanwhile calling `drawer.getExpandableExtension().expand()` seems to either rarely work, or be immediately cancelled out by something triggering the collapse. And the most curious part is, the `ExpandableExtension.collapse()` method does **not** get called, yet the items become magically collapsed.

**Comment by mikepenz** [comment]
@NoHarmDan please transfer this into a new ticket
