### ISSUE TITLE
Q - Handle 2 layouts

### ISSUE THREAD

**Issue by LinkOut** [mikepenz/MaterialDrawer#1375]
Hi, very nice lib. 
I was wondering if there is the possibility to handle 2 different layouts using one drawer.
The situation is when the user's not registered to the app, that means the drawer supposed to bring the user to login/registration, when the user are logged in, it supposed to show its features.

Is it possibile with this lib?

thanks a lot.

**Comment by mikepenz** [comment]
@LinkOut you can build and fill the drawer with different items depending on the current status, and you can then just alter those items and notify the drawer about the update as soon as the user gets logged in.

https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

**Comment by LinkOut** [comment]
Hi, thank you for the response, so iam supposed to start with an empty drawer layout and then just "inflate" items inside it? The problem is that my "empty" layout is a full custom layout.

**Comment by mikepenz** [comment]
@LinkOut if you are not using the `MaterialDrawer` with the items it provides and use custom layout for all it may is the wrong library for you. because the drawer can't do anything special for you then. 

If you use the items, just fill in the items, and notify the drawer about updated items. and if the state changes you can then switch the items and notify the drawer again. 

I can give you support for a 100% custom layout

**Comment by LinkOut** [comment]
Ok, pretty clear. How about change burger color? Where does it takes the color from?

**Comment by mikepenz** [comment]
that's nothing from the drawer. The drawer just adds the `ActionBarDrawerToggle` please search on google how to color the `ActionBarDrawerToggle`
