### ISSUE TITLE
Fix for whenever ViewPager crashes when using this library

### ISSUE THREAD

**Issue by zunjae** [mikepenz/MaterialDrawer#1475]
I have no idea where to post this, however I want to share this because I know other people could also experience this problem.

It seems as if this library is using a newer version of support:design, as a result, developers need to add a method in their Adapter class to prevent crashes.

This is the code I used:

```java
    @Override
    public void unregisterDataSetObserver(DataSetObserver observer) {
        if (observer != null) {
            super.unregisterDataSetObserver(observer);
        }
    }
```

( I used `com.android.support:design:23.1.1`, though after importing your library I got an error. Adding the method fixed the issue)

**Comment by mikepenz** [comment]
The latest version of my libs always come with the latest support libraries. In this case 24.1.1
(https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L8) 

Issues or changes required due to updates should always be looked up in the official changelog for those. 

Still thank you for adding the info here, so if someone comes across it, he finds it using the search function
