### ISSUE TITLE
icons size

### ISSUE THREAD

**Issue by hharddy** [mikepenz/MaterialDrawer#1477]
how can i change the size of icons?

**Comment by mikepenz** [comment]
@hharddy the icons are defined in the size as defined in the `Material Design Guidelines` there are smaller ones possible via the `SecondaryDrawerItem`. 

If those does not fit your needs, you may also be able to change the size (when using the `IconicsDrawable`) by just setting more padding to those. 

Otherwise this will require you to overwrite the default layouts (and dimens.xml) for those items. (or you create a `CustomDrawerItem`)

**Comment by mikepenz** [comment]
Regarding `CustomDrawerItem` 
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
