### ISSUE TITLE
Drop API 10 support

### ISSUE THREAD

**Issue by marbat87** [mikepenz/MaterialDrawer#1492]
Why this sudden change??
Google still supports API 9..

Please think again about it.

Regards,
Marcello

**Comment by Rainer-Lang** [comment]
I think it's the right way to move on. API 14 is really enough. Sometimes it's just not right for the codebase to keep such old things alive.

@marbat87 Please have a look here: https://developer.android.com/about/dashboards/index.html 
Open-source freetime project contributors aren't Google which earns a bit more ;)
Have you thought about this? :)

**Comment by marbat87** [comment]
But in this case I don't see a clear reason, because minimal changes have been made along with the api support drop.
And the library works almost perfectly as is.

**Comment by Rainer-Lang** [comment]
Mike doesn't only support/develop/maintain this MaterialDrawer lib. He has a lot of others.

Other way around: Why do you need such a low api level? Is this really necessary? Maybe you are able to increase your level too.
Do you really have so many users in sooooo low api levels? :)

**Comment by marbat87** [comment]
I know that he doens't develop this library only. Indeed changes are minimal in other libraries too, in my opinion ;)
However I have still 1200 users on 30k who are on API 10... It is not so negligible :(

**Comment by mikepenz** [comment]
@marbat87 as mentioned in the changelog. You can stay with the previous version. I will no longer support API 10. 

If updates are really necessary for you, you can always just download the source and add the libraries as modules and modify them to work. 

It is 2016 it is time for API 14. API 10 is really no longer necessary.

**Comment by marbat87** [comment]
"It is 2016 it is time for API 14. API 10 is really no longer necessary."
Usual answer that doesn't give a real answer or a real reason..

I'm a bit disappointed, however great work and keep coding.

Best wishes.

**Comment by Rainer-Lang** [comment]
@marbat87 Sometimes a developer just want to go further (or has already plans for the future). I could completely understand Mike. His libs are the best supported I know.
Sometimes a decision seems hard or unfair - BUT at the end of the day the situation is better than before. :)

**Comment by marbat87** [comment]
@Rainer-Lang  Well, after 2 weeks spent on integrating these libraries, I can't agree with your last phrase O.o.
However life goes on.

Regards.

**Comment by mikepenz** [comment]
@marbat87 the current versions are really stable. and there shouldn't be the need of any changes on my side. you can even go with support lib updates by just excluding those of my libs. So you are still fine for the upcoming months. And by the time you will also end supporting API 10. 

I know a lot of huge apps which go to API 16 already. In most cases you can ignore users for API < 14. (Just some apps may require to support those)

As mentioned already before. You can still use the libs. You can also bring back support for API 10 easily if required. I just can't support those anymore. The last phones which are on those API levels broke. And I can't support something which I can't test. And I clearly want to spend time to improve and extend the libraries instead of spending time to test on android versions which are really old and which I can't test anymore on real devices. 

Just as an addition. API 10 - 14 was there in 2010 - 2011. That was support for 5 year old Android versions from my side. 

Not even apple supports devices from 2010 with their latest software updates. And they just got a handful...

**Comment by marbat87** [comment]
@mikepenz 
This is a real answer, thank you.
Just a clarification, how can I do the following?
"you can even go with support lib updates by just excluding those of my libs"

Regards,
Marcello

**Comment by mikepenz** [comment]
@marbat87 you can do this similar to this:
https://github.com/mikepenz/FastAdapter/blob/develop/app/build.gradle#L71
Just use the module name of the support libs. And then define the dependency in your build.gradle with the version you want to use it with. 

As of the stability. If you look at the releases from the past weeks there were no huge changes or no big issues anymore. Just some special cases which you may will never run into.

**Comment by siavashabdoli** [comment]
what is the last version of project that support api 10?
@mikepenz

**Comment by mikepenz** [comment]
@siavashabdoli https://github.com/mikepenz/MaterialDrawer/releases/tag/v5.5.0
