### ISSUE TITLE
Q - Custom font?

### ISSUE THREAD

**Issue by LinkOut** [mikepenz/MaterialDrawer#1516]
How to set custom font? (text)

**Comment by mikepenz** [comment]
You can provide a `Typeface` to all default drawerItems: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/BaseDrawerItem.java#L203 

otherwise you will be able to do so with calligraphy. or you have to adjust the layouts used by the drawer. (as those do not allow to define a typeface by default).

**Comment by devabir93** [comment]
Hello, actually i am using calligraphy for the whole app but its not applied for drawer, why that?

**Comment by mikepenz** [comment]
@devabir93 the drawer content itself is simply a recyclerView with views added to it. This happens dynamically. I have no idea how calligraphy handles recyclerViews and their content, and couldn't find documentation about it. This is most likely an issue with calligraphy and not with this library
