### ISSUE TITLE
AccountHeader.updateProfile(profile) does not update image in header

### ISSUE THREAD

**Issue by mpost** [mikepenz/MaterialDrawer#1569]
When the selected profile is updated (eg with an image), the change is not applied in the header area. Eg. same avatar icon and email etc is used.

```java
accountHeader.updateProfile(profile); // no effect on header view
```

Opening the account chooser shows that the avatar image is in fact attached to the profile

**Comment by mpost** [comment]
Okay, from the docs it was not fully clear what was going on. The update only applies to the header section when the profile has an identifier set. This requirements should either be made clearer or the update should throw an exception when no id is provided in the profile.

**Comment by mikepenz** [comment]
@mpost the changes will only show up in the profile list with some luck, depending on the `RecyclerView` invalidating the views, because it will take the same object which you changed. 

For the header the displaying of the updated item requires some logic to be executed. 

In general nothing happens at all if there is no identifier:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L254

But yes you are right it may be good to output some log messages or something in this case.

**Comment by mikepenz** [comment]
In general the javadoc already mentions this:
https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/AccountHeader.java#L240
