### ISSUE TITLE
onItemClick fired multiple times?

### ISSUE THREAD

**Issue by mshi** [mikepenz/MaterialDrawer#165]
Hi Mike,

Is there a reason why the `onItemClick` event is fired multiple times at multiple positions in `Drawer.OnDrawerItemClickListener`?

I'm determining what is clicked by the `position` in the handler, but I'm getting multiple values for a single click. Eg. I clicked on the first item, but that event was called 3 times with positions 1, 5 and 8.

Thanks!

**Comment by mshi** [comment]
Nevermind! I dug through the code and found that setSelected fires the event handler, and i should call the one where it doesn't fire.

**Comment by mikepenz** [comment]
@mshi can you be a bit more specific about the issue. there should only be one event for a single item?

**Comment by VeeruPV** [comment]
I guess what the OP meant was, Drawer Item tapped event gets fired multiple times, in fact in a loop hanging the app. This is because of the old code where setSelection(drawreItem) was used. The new version, from my understanding re-fires the event on setSelection() cause an indefinite loop. 

The setSelection() is not needed anymore. 

Thanks

**Comment by mikepenz** [comment]
@VeeruPV i never had any problems with set selection. do you have problems with it?
