### ISSUE TITLE
Espresso test mini drawer perform action click on item

### ISSUE THREAD

**Issue by PabloDesiderioFlores** [mikepenz/MaterialDrawer#1687]
Hi, I have a mini drawer and I want to do ui test on this with Espresso.
I don't know if I a have to open the mini drawer first or I have to perform click with mini drawer closed.
Anyway, I tried this just for see what happen, but I have an error that the view is not on the hierachy. This code I saw here in another issue for open the drawer. I have a mini drawer. I know that I have to work like a recyclerview to do clicks because in builder there is a recycler. 

`// Open Drawer to click on navigation.
        onView(withId(R.id.material_drawer_layout))
                .check(matches(isClosed(Gravity.LEFT))) // Left Drawer should be closed.
                .perform(open()); // Open Drawer`

and then 

` onView(withText(R.string.prices_list))
                .perform(click());`

With this code: 
`onView(withId(R.id.material_drawer_layout)).perform(DrawerActions.open());`

I have the same result.

**Comment by mikepenz** [comment]
@PabloDesiderioFlores hi. Have you found a solution already?

The `MiniDrawer` is no `DrawerLayout` so that code won't work. The `MiniDrawer` is inside a `SlidingPaneLayout` which behaves differently. I expect there not to be available pre-recipes for espresso. 

Please report back if this is still a topic and reopen if yse
