### ISSUE TITLE
I get No static method setOnApplyWindowInsetsListener Error after adding library

### ISSUE THREAD

**Issue by tux-world** [mikepenz/MaterialDrawer#1688]
after adding this library on gradle and sync that, i get this error:

```
Process: com.pishguy.androidapplication.cafemaku, PID: 24770
java.lang.NoSuchMethodError: 
No static method setOnApplyWindowInsetsListener(Landroid/view/View;Landroid/support/v4/view/OnApplyWindowInsetsListener;)
V in class Landroid/support
/v4/view/ViewCompatLollipop; or its super classes (declaration of 
'android.support.v4.view.ViewCompatLollipop' appears in /data/data
/com.pishguy.androidapplication.cafemaku/files/instant-run/dex/slice-internal_impl-
25.0.1_998390981b8fe27eebbe2050c1adf24fba9bcb95-classes.dex)
 at android.support.v4.view.ViewCompat$LollipopViewCompatImpl.setOnApplyWindowInsetsListener
```

**Comment by mikepenz** [comment]
what support library version does your project use? Please always use the latest support libraries in combination with this lib. (or exclude them)

**Comment by tux-world** [comment]
@mikepenz i'm using latest version of this library sir

**Comment by mikepenz** [comment]
I meant of the "support libraries"

**Comment by tux-world** [comment]
```
compile('com.android.support:support-v4:24.0.0') {
        force = true;
    }
    compile 'com.android.support:appcompat-v7:24.0.0'
    compile 'com.android.support:cardview-v7:24.0.0'
```

**Comment by tux-world** [comment]
@mikepenz whats ```${versions.supportLib}``` on your gradle file sir?

**Comment by mikepenz** [comment]
it is a reference to the root build.gradle version:
https://github.com/mikepenz/MaterialDrawer/blob/develop/build.gradle#L8

you have to use the smae support lib version for all the libs, otherwise such issues occur. 
And I highly recommend you to update yours too to 25.1.0

otherwise you have to exclude the support libs of the MAterialDrawer

similar to this snippet: http://stackoverflow.com/a/27116437/325479
