### ISSUE TITLE
Is there any way to open drawer from Right side of screen?

### ISSUE THREAD

**Issue by Reza-Rg** [mikepenz/MaterialDrawer#174]
Is there any way to open drawer from Right side of screen, it's more suitable for RTL language.

**Comment by mikepenz** [comment]
@Reza-Rg yes. `.withDrawerGravity(Gravity.RIGHT)`

**Comment by Reza-Rg** [comment]
Thank you. That's great. I didn't see that.
But in this case, can we customize that icons, to be in right of titles? I mean how to exactly mirror current drawer.

**Comment by mikepenz** [comment]
If you want the icons also on the right side you have to overwrite the layouts by adding RTL drawer layouts to your source. they are not in the drawer because i can't test. should be possibly by just copying over the current drawer layouts and replace left with right. 

Sorry about this. but adding something untested is not a good idea. also there are some people who do not want rtl layout on rtl phones ;)

**Comment by Reza-Rg** [comment]
Ok, Thanks for your great library, I will fork it and try to add rtl function.
:)

**Comment by mikepenz** [comment]
ok great ;). if you plan to do a pull request, keep in mind simply adding the layouts is probably a bad idea because this will automatically switch to the rtl layout for all rtl phones / languages and some people don't like this. best would be if you get current layouts working to simply support both. but i was not able to do this without the possibility to test both :/

**Comment by Reza-Rg** [comment]
Yeah, I would try to add rtl function without interrupting lib at all! :) just a tweak of supporting both.

**Comment by mikepenz** [comment]
@Reza-Rg would be awesome ;)

**Comment by ccj22** [comment]
airbnb is on the right side.
