### ISSUE TITLE
ProfileDrawerItem Icon Centering Problem

### ISSUE THREAD

**Issue by Queskr** [mikepenz/MaterialDrawer#1746]
Hi,

I'm using the header to show additional account info, creating ProfileDrawerItem with icons, such as: 

profileItem = new ProfileDrawerItem().withName(details).withIcon(getResources() .getDrawable(R.drawable.ic_group_type_regular)).withEnabled(false).withSelectable(false);

For some reason, the icons are circled and not centered correctly (see below).
Any idea how to fix it?

![screenshot_2017-02-18-10-38-14](https://cloud.githubusercontent.com/assets/17469969/23091823/7837fffa-f5c7-11e6-8eee-fda801958e82.png)

**Comment by mikepenz** [comment]
@Queskr the icons are circled as specified in the google material guidelines. 
Your icons may have wrong dimension that's why the CircleImageView displays them wrong. 

If you need a different behaviour. Create a custom ProfileDrawerItem.
Or you overwrite the layout of the ProfileDrawerItem and replace the BezelImageView with a normal ImageView

https://github.com/mikepenz/MaterialDrawer/blob/fed00a199196efbc63296a081723e603647b5bc4/library/src/main/res/layout/material_drawer_item_profile.xml#L22

**Comment by Queskr** [comment]
Thanks!
