### ISSUE TITLE
i want to make it open  in right but icons still in left so how i make it to right ? 

### ISSUE THREAD

**Issue by TaherZaki** [mikepenz/MaterialDrawer#175]
in details please cause i need it

**Comment by mikepenz** [comment]
@TaherZaki you can open the drawer on the right by defining it's gravity. 

by default the MaterialDrawer does not come with RTL support because 90% of all devs don't need this. also it will cause some issues for devs who have rtl languages but still want the drawer to be non rtl. 

you can simply copy the drawerItem xml's into your project and change the layout so it's rtl. they will automatically overwrite the original xml's (if they stay the same name). 

to make it easier for others it would be great if you can send them here. so i can include them in a folder for copy and paste (if devs require them)

**Comment by TaherZaki** [comment]
Thanx man  great work
