### ISSUE TITLE
Diferent color/textsize in ProfileDrawerItem, to name/email.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#178]
Diferent color/textsize in ProfileDrawerItem, to name/email.
This is possible?

**Comment by wKovacs64** [comment]
You should be able to use `.withTextColor()` or `.withTextColorRes()` for color. You can change the typeface using `.withTypeface()` but I don't see anything for size.

**Comment by Grozny** [comment]
what I want is for example: name - textsize 12sp and color #646464, email - textsize 14sp and color #FFFFFF.

**Comment by wKovacs64** [comment]
That doesn't appear to be possible at this time. Both name (if shown) and email will get the same color and there is no size option.

The Typography section of the [Material Design guidelines for the Navigation Drawer](http://www.google.com/design/spec/patterns/navigation-drawer.html) specifically indicate a fixed size of 14sp and the same color for both name and email. That might be why these options are not supported, but I defer to the author.

**Comment by mikepenz** [comment]
@wKovacs64 thanks for answering ;) and helping.

@Grozny yeah i have not added the size options because the Material Design Guidelines specify the exact font size of 14sp. If you really want to have different font sizes. you can either overwrite the dimensions within your dimens.xml (you can find all set dimensions here: https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/dimens.xml)

or you create your own DrawerItem implementation
