### ISSUE TITLE
How enable rippleview effect?

### ISSUE THREAD

**Issue by Imangazaliev** [mikepenz/MaterialDrawer#186]
Hello. How enable rippleview effect in items and how change background color of the drawer ? Thank's

**Comment by mikepenz** [comment]
@Imangazaliev the ripple effect is only enabled vor devices starting with api level 21. it is enabled by default. the ripple effect won't be included on earlier android devices. google hasn't included it in the support library.

changing the background is really easy. you can overwrite the color via the color.xml or via a theme overriding one of my themes. or you use one of the methods provided by the Drawer... `withSliderBackgroundColor`

**Comment by Reza-Rg** [comment]
But it would be great if it was possible to enable ripple effects on pre 21 api level. Actually, there are plenty of libraries which enable ripple effect for +9 api level.
Right now, my whole app has ripple effects except drawer. :((

**Comment by mikepenz** [comment]
@Reza-Rg as mentioned above there won't be any 3rd party lib mimicking the ripple effect. Google has specified in the guidelines that there should not be a ripple effect on pre 21 api level devices. It also has not included it into the support library because it's performance is not good enough.

If you really need it. Just implement your custom DrawerItem.
