### ISSUE TITLE
Getting lags with clicking profile image and account list item.

### ISSUE THREAD

**Issue by sweetdream0729** [mikepenz/MaterialDrawer#1896]
Hi,

Great library.
But after I click profile image or select account multiple times, it is getting lags.
Side menu seems to get bad performance after click account multiple times.
Please help me with this issue.
Thanks.

**Comment by mikepenz** [comment]
@sweetdream0729 can you reproduce this in the sample application? 
Do you have too big images set for the profiles or for the header?

**Comment by sweetdream0729** [comment]
It is also happening when I select account on account list.

**Comment by mikepenz** [comment]
In the sample app?

**Comment by mikepenz** [comment]
@sweetdream0729 is the problem happening for you in the sample app? 

If not (and I can not see this problem in the sample app) then the issue is very likely related to some of your code or ressources. 

As mentioned are your images (for the profiles) to big? do you have a huge header image? Anything else?

**Comment by sweetdream0729** [comment]
Sorry, for delay.
I have tried to use profile images of your sample app.
But it is still getting lags.

**Comment by mikepenz** [comment]
@sweetdream0729 which phone do you use? can you please record a video?

**Comment by mikepenz** [comment]
Close until more information is provided
