### ISSUE TITLE
Selected wrong item with setStickyFooterSelection and withStickyFooterDivider(true)

### ISSUE THREAD

**Issue by sosite** [mikepenz/MaterialDrawer#1924]
When I use `setStickyFooterSelection(identifier, false/true)` with `withStickyFooterDivider(true)` drawer settings then I have selected wrong item (higher one) on the bottom sticky items.

Btw - it's a little confused that `setSelection(identifier, false/true)` doesn't try to select sticky item too 😉

**Comment by mikepenz** [comment]
@sosite well sticky footer items are just a tiny addition. in general those are mainly used in situation without a selection at all. so that's why `setSelection()`  does not care about them, and will never care about them :D

and about the issue, sounds like I miss to add +1 thanks to the additional layout in the `LinearLayout` holding the sticky items
