### ISSUE TITLE
Custom drawer contents

### ISSUE THREAD

**Issue by Zhelyazko** [mikepenz/MaterialDrawer#1969]
Great lib! It's the first time I'm using it and it's quite powerful.

I've implemented custom sticky header that has a functionality similar to the account picker.
When a user taps a button the contents of the drawer below the sticky header should change and display something like a list of accounts.
I was wondering if I can display custom layout below the sticky header? I already have RecyclerView with Adapter etc. from my previous implementation and I thought I could re-use them. I see that I can create custom Drawer item and generate a new set of items to be displayed in the drawer using switchDrawerContent() but it's kind of a workaround.

Is there any other way to display custom content/layout in the drawer?

**Comment by mikepenz** [comment]
@Zhelyazko well you don't have to use `switchDrawerContent()` that one was basically designed for keeping 2 different sets (like the use case for the `AccountHeader`) Even without that method you can add and remove item's during runtime. 
https://github.com/mikepenz/MaterialDrawer#modify-items-or-the-drawer

The item (CustomDrawerItem's) have to implement the `IDrawerItem` interface. Which basically combines model + UI code (which you would normally write in an adapter)

Well the layout can be replaced, but only while building. and it breaks the purpose of the `MaterialDrawer` somehow. I'd recommend you to make your element you want to display as `CustomDrawerItem` (see the samples. they can be quite simple, the default items are more complex as they have to provide many settings and configuration options) 

Otherwise. The Drawer object gives you access to the `View`'s so you can theoretically add your own `RecyclerView` and display it above the default one (set visibility gone) but I can't really give support for that use-case

**Comment by Zhelyazko** [comment]
Thanks for the information. That's more than enough. I've been looking into the default `IDrawerItem` implementations but I haven't checked the samples - will do now!

**Comment by mikepenz** [comment]
Ok great.
