### ISSUE TITLE
How to reduce gap between two navigation Item

### ISSUE THREAD

**Issue by ravigupta9363** [mikepenz/MaterialDrawer#1977]
how can reduce gap betwwen two navigation item in menu bar help me

**Comment by mikepenz** [comment]
@ravigupta9363 the default provided drawer items follow the google material design guidelines. And I highly suggest you stick with it. 

Otherwise you can adjust some values here: https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/values/dimens.xml

And if you need total custom behaviour. Have a look on how you can implement a `CustomDrawerItem`
https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_modify_add_custom_draweritems.md
