### ISSUE TITLE
Control size of text in elements

### ISSUE THREAD

**Issue by cmonfortep** [mikepenz/MaterialDrawer#198]
Is it possible to control de text size of the elements like ```PrimaryDrawerItem```or others?

**Comment by raghunandankavi2010** [comment]
If you look @ https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/dimens.xml line 31 its      <dimen name="material_drawer_item_primary_text">14sp</dimen> which meets the material design guidelines @ http://www.google.co.in/design/spec/patterns/navigation-drawer.html. So why do you want to change the text size?.

**Comment by mikepenz** [comment]
@raghunandankavi2010 thanks for answering.

@cmonfortep you can overwrite it via dimension. there won't be a call to do so, because the default provided items follow the Android Design Guidelines and there is no space for other text sizes. 

You can implement your own DrawerItem if you really want to change it during runtime

**Comment by cmonfortep** [comment]
Thanks, I know that the default values of this library are following the android design guidelines, but sometimes a client could ask for other sizes.

**Comment by mikepenz** [comment]
@cmonfortep if something not default is required i recommend to implement a custom DrawerItem or changing the values via the dimens.xml
