### ISSUE TITLE
Is there any way to alter what happens when profile header is clicked when a mini drawer is closed?

### ISSUE THREAD

**Issue by prateek-dhanuka** [mikepenz/MaterialDrawer#2023]
I am making an application for college and would like to display a students profile when the profile image is clicked when the mini drawer is clicked while retaining the ability to change profiles when drawer is expanded. Any  way to achieve this? Thanks in advance.

Edit: Basically, I want that on pressing the profile image in a mini drawer when it is collapsed (pointed in figure) should show profile info.
![screenshot3](https://user-images.githubusercontent.com/30016175/30119290-e0ff03ee-9342-11e7-9e78-39ebad384a41.jpg)

But the profiles should work as it is when mini drawer is expanded.
![screenshot2](https://user-images.githubusercontent.com/30016175/30119345-050516a2-9343-11e7-9012-867787ca828a.jpg)

**Comment by mikepenz** [comment]
@prateek-dhanuka could you please be a bit more specific?

so you only want to react on the `MiniDrawer`s profile click?

**Comment by prateek-dhanuka** [comment]
I edited the question to include more details.

**Comment by mikepenz** [comment]
@prateek-dhanuka you want to intercept the `MiniDrawer`'s header click. 
you might be able to achieve this by listening for the item click listener, and if the current state is == miniDrawer you do your own custom action and consume the event, otherwise you keep the default and do not consume the event
