### ISSUE TITLE
Can I use the CrossFader effect wihout MiniDrawer ?

### ISSUE THREAD

**Issue by Kintaro37** [mikepenz/MaterialDrawer#2049]
Hi,
I am using your [CollapsingToolbarLayout](https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/CollapsingToolbarActivity.java) implementation
```
result = new DrawerBuilder()
                .withActivity(this)
                .withAccountHeader(headerResult)
                .withToolbar(toolbar)
                .withFullscreen(true)
                .withGenerateMiniDrawer(true)
...
```
I would like to create the "sliding" effect for the drawer - like the one in the MiniDrawer - but with CollapsingToolbarLayout. 
In other words, I want the drawer to "push" the main layout to the right instead of covering it.
How can I achieve this ?

Thanks a lot for your great library

**Comment by mikepenz** [comment]
@Kintaro37 that's not supported by the `DrawerLayout` as far as I know. It's not related to this project, as the `DrawerLayout` is provided by google

**Comment by Kintaro37** [comment]
Ok, thanks for your answer. Could you just let me know if it is possible to add manually a Crossfader to the DrawerBuilder ? Or if I am wasting my time...
Also do you confirm that from your library, it is necessary to use a MiniDrawer or PersistentHeader to obtain the sliding effect?

**Comment by mikepenz** [comment]
@Kintaro37 look into the samples I already have a huge collection of different things. 

you can have a collapsing header and a normal `DrawerLayout` 

if you use the `MiniDrawer` or the `Drawer` in your view hierarchy that won'T work as it is not in a scrolling container and will just cause problems.

if you want to have only crossfading effect with a drawer then you might want to have a look on the `CrossfadeDrawerLayout` 

the `Crossfader` would not cause the content to move to the right instead of blurring. that's only a thing fro the `DrawerLayout` you might find one which does this effect instead of the color overlay

**Comment by Kintaro37** [comment]
Thanks for the info Mike, I'll try with CrossfadeDrawerLayout
