### ISSUE TITLE
why latest version forces to sdk 26?

### ISSUE THREAD

**Issue by nrazon** [mikepenz/MaterialDrawer#2055]
I am upgrading to 5.92 to 5.9.5 but it breaks my application because I am not targeting latest sdk 26.
sdk 26 has still alpha dependencies so I don't want to target it until it matures.

Why library need us to have targetSdk : 26? 
Can't we use latest materialdrawer version while targeting sdk 25?

**Comment by mikepenz** [comment]
the latest support libs require the latest sdk version.

**Comment by forcemagic** [comment]
There is no such thing as `com.android.support:appcompat-v7:26.0.0`. That's not me talking. It's Android Studio. There's only `com.android.support:appcompat-v7:26.0.0-alpha1`, but that's not a dependency of this library. Basically, Gradle Sync can't complete, because of unmet (and nonexistent) dependencies. I didn't want to open a new issue, but if I have to, just tell me :smile: 

Oh, and another thing. If I remove `transitive=true` from the build file, I get... this:

```
AGPBI: {"kind":"error","text":"Error retrieving parent for item: No resource found that matches the given name \u0027MaterialTheme\u0027.","sources":[{"file":".../app/build/intermediates/res/merged/debug/values/values.xml","position":{"startLine":1915}}],"original":"","tool":"AAPT"}
ar.ActionBar.TranslucentStatus\u0027.","sources":[{"file":".../app/build/intermediates/res/merged/debug/values/values.xml","position":{"startLine":2102}}],"original":"","tool":"AAPT"}
```

**Comment by mikepenz** [comment]
if you need something else or lower support libs version you can always exclude those
