### ISSUE TITLE
Profile without icon

### ISSUE THREAD

**Issue by fgagneten** [mikepenz/MaterialDrawer#2072]
Is there a possibility to make a profile without icon? I want to show a profile just with the name and email of the user.

Thanks.

**Comment by mikepenz** [comment]
@fgagneten you have to create a `CustomProfileDrawerItem` if you don't want to hide the profile icon, passing no url will fallback to the default icon. you can chagne the placeholder icon to be transparent though. 

if you want no icon at all (this is not supported out of the box because it'snot in the material design guidelines) you want to do the above + also modify the xml of the header to hide the icon views (or you use the compact view)

**Comment by fgagneten** [comment]
Thanks @mikepenz, but How can I modify  xml of the header? Could you give steps for doing that? I compile your library with gradle dependency.
Thanks.

**Comment by mikepenz** [comment]
@fgagneten just copy paste the xml over. you don't have to do anything else. it will be automatically replaced by the build setup. 

perhaps you want to make it 0 size, or alpha 0 or anything. I think the visiblity is updated somewhere in the code.
