### ISSUE TITLE
Zebra Effect on Menu Items

### ISSUE THREAD

**Issue by MatyasK** [mikepenz/MaterialDrawer#2112]
Hi Mike again,

Is it possible to achieve the Zebra effect on menu items? So first is white, second green, third white...

Thanks again,
Matyas

**Comment by kaloglu** [comment]
If I want do that I'll try to extend drawerItem class with custom view

**Comment by mikepenz** [comment]
@MatyasK as @kaloglu already correctly pointed out. You'd need to create your own `CustomDrawerItem` which set a different background depending on it's position. 

the `viewHolder` should have the `adapterPosition` which theoretically can be used. remember if you add a new item somewhere, you'll have to notify the whole adapter about changes as it wouldn't change the "zebra effect" otherwise. 



(thanks @kaloglu for answering :) )
