### ISSUE TITLE
NullPointerException when using android.R.id.content

### ISSUE THREAD

**Issue by danhawkes** [mikepenz/MaterialDrawer#220]
If the host activity doesn't explicitly set a layout (because it relies on `android.R.id.content`), the content 
view [here][1] is null.

After giving it some thought, I don't think it's a good idea to use the root view, as it's either going to be placed inside the root fragment's view hierarchy (if `build()` is called after adding a fragment), or it's going to be replaced the first time a fragment is added with `FragmentTransaction.replace()`.

Suggest explicitly disallowing use of the root view, and possibly null-checking and throwing a more explicit exception when the root view has no children.

What do you think? 

[1]: https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/Drawer.java#L985

**Comment by mikepenz** [comment]
@danhawkes in 99% of all cases you can use the root layout. Also the MaterialDrawer library depends on inflating and changing the users layout. this makes everything easier for most use cases. 

If you can't use the default inflating. You can still use the .buildView method and let the drawer handle the view instead of the complete layout and style. You will then have to create the DrawerLayout on your own. 

Easiest solution for you. Create a really flat layout which you set. This won't add such an overhead for the system and you can still use the drawers default generation

**Comment by mikepenz** [comment]
@danhawkes with the newest version i will now throw an runtime exception with the description what to do :D

**Comment by danhawkes** [comment]
@mikepenz Excellent, thanks!
