### ISSUE TITLE
Image not coming properly in circular view. 

### ISSUE THREAD

**Issue by rohit85111** [mikepenz/MaterialDrawer#2214]
![screenshot_2018-02-09-14-37-52-050_com bind android](https://user-images.githubusercontent.com/36294860/36020012-20d4030a-0da7-11e8-930d-f03ed8b4d4d4.png)
## About this issue

- Briefly describe the issue
- How can the issue be reproduced / sample code

## Details
- [ ] Used library version
- [ ] Used support library version
- [ ] Used gradle build tools version
- [ ] Used tooling / Android Studio version
- [ ] Other used libraries, potential conflicting libraries

## Checklist

- [ ] Searched for [similar issues](https://github.com/mikepenz/MaterialDrawer/issues)
- [ ] Checked out the [sample application](https://github.com/mikepenz/MaterialDrawer/tree/develop/app)
- [ ] Read the [README](https://github.com/mikepenz/MaterialDrawer/blob/develop/README.md)
- [ ] Checked out the [CHANGELOG](https://github.com/mikepenz/MaterialDrawer/releases)
- [ ] Read the [FAQ](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ.md)
- [ ] Checked out the [MIGRATION GUIDE](https://github.com/mikepenz/MaterialDrawer/blob/develop/MIGRATION.md)

**Comment by rohit85111** [comment]
Image not coming properly in the circular image view. how to fix it.

**Comment by mikepenz** [comment]
@rohit85111 the image you should provide should be a square. most image loading libraries are capable to do this. (glide, picasso, ..)


Otherwise you will have to include the header xml in your project and define the `scaleType` used for the `BezelImageView`s

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/res/layout/material_drawer_header.xml#L17

**Comment by rohit85111** [comment]
@mikepenz scaleType worked for me thanks
