### ISSUE TITLE
Working with fab (floating action button)

### ISSUE THREAD

**Issue by IlyaMyasoedov** [mikepenz/MaterialDrawer#225]
Thanks for your lib. You are the best!  I am using it for my project. But i have some difficulties  with fab. When I open the navigation drawer, it does not cover the FAB, and the button appears on top of it. I would like to avoid hiding the button and showing it on drawer open/close as that is rather distracting. Could you add method onDrawerSlide(View drawerView, float offset) to your implementation of Drawer?

**Comment by mikepenz** [comment]
@IlyaMyasoedov you can modify the width of the drawer already if this is the thing you want. 

if the fab is in front of the drawer. i assume it has an higher translationZ or elevation than the drawer. You can either add an higher elevation to the drawer or a lower one to the fab.

**Comment by IlyaMyasoedov** [comment]
Thank you for reply. But attribute "android:elevation" is only used in API version 21 and higher. My min version is 16

**Comment by mikepenz** [comment]
@IlyaMyasoedov is the fab above the drawer on lower api versions?

**Comment by IlyaMyasoedov** [comment]
Mike! It seems to me that attribute "android:elevation" has no effect on my device ZTE V975 with API 17. Thanks for your help.

**Comment by mikepenz** [comment]
@IlyaMyasoedov so i asked if it's above the drawer on lower api versions too :D

i know that elevation won't be used below 21. 

i just want to know how it displays the fab. to see how it's possible to overlap the drawer

**Comment by IlyaMyasoedov** [comment]
@mikepenz I can give you a small project for demonstration, There are a fab and driver in it. It was developed in Android Studio 1.1.0. Link to download https://yadi.sk/d/rSw186kYg2Pt6

**Comment by mikepenz** [comment]
@IlyaMyasoedov i'll report back as soon as i have any news. thanks

**Comment by mikepenz** [comment]
@IlyaMyasoedov ok the issue is quite easy to solve and quite easy to understand


Each activity contains of an root layout identified by 'android.R.id.content' this will host the complete layout of your activity. So if you use my library i will take all layouts hosted within this content layout and will inflate it within a drawer. so i do the DrawerLayout by code for you and will manage everything. nothing to handle from your side. Now you come and add the FAB to your activity. 

The fab also contains some similar code as the drawer. if you don't provide the layout which will host this fab it will inflate it within 'android.R.id.content' layout so it will be in a layout which is the parent of the drawer (because we added the drawer earlier). So there are two solutions. you can either inflate the FAB before the drawer. I don't recommend this because it will create another layer within your view hierarchy and this is not needed. 
The cleanest solution is to add the view which will host the fab, and that's the content of the DrawerLayout. You can do this like this:

```java
//look at the part with .in(...)
mFloatingAction = FloatingAction.from(this)
                .listenTo(mListView)
                .in(drawerResult.getContent())
                .colorResId(R.color.windowBackground)
                .icon(R.drawable.plus)
                .listener(this)
                .build();
```

After this the drawer will be above the fab. 

I also saw an additional issue. Your activity_main.xml contains a DrawerLayout which is really unnecessary. It won't be used it will just add another view which hosts the rest of the layout. I recommend to remove it, because the MaterialDrawer handles this for you ;) Keep it simple :D


Here's the updated layout:


```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <include
        android:id="@+id/relative_actionbar"
        layout="@layout/toolbar_default"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <FrameLayout
        android:id="@+id/container"
        android:layout_width="match_parent"
        android:clickable="true"
        android:layout_height="match_parent"
        android:layout_below="@+id/relative_actionbar">
        <ru.logomotiv.android.whattobuy.floatingaction.ChattyListView
            xmlns:android="http://schemas.android.com/apk/res/android"
            xmlns:tools="http://schemas.android.com/tools"
            android:id="@android:id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:divider="@null"
            tools:context="ru.logomotiv.android.whattobuy.MainActivity"
            android:drawSelectorOnTop="true"/>
    </FrameLayout>
</RelativeLayout>
```

Oh and one more thing. The drawer includes an util called 'KeyboardUtil'. Perhaps you like the method called `.hideKeyboard()`,

**Comment by IlyaMyasoedov** [comment]
@mikepenz Thanks :) The solution is quite easy) Good luck! I close the issue.
