### ISSUE TITLE
Inconsistent setter API in BaseDrawerItem

### ISSUE THREAD

**Issue by danhawkes** [mikepenz/MaterialDrawer#227]
Just spent some time trying to figure out why `setName()` was not working to update a drawer item.

Was calling `withName(int)` in the initial setup, then `setName(String)` to update it. It looks like the `convertView()` treats the int ID as taking precedence, so unless I also call `setName(-1)`, the string value will never be displayed.

IMO this is inconsistent and confusing - the builder adopts the Android idiom of using overloads for setters (e.g. there's `setName(int)` and `setName(String)`, but the DrawerItem has `setName(String)` and `setNameRes(int)`. 

Looking at the `Drawer` API I see there are `updateName()` utility functions that do this, but presumably they're provided as a convenience because they also invalidate the list. For more complicated updates (e.g. "I want to manipulate the properties of various DrawerItems, and update them atomically"), users need to be aware of this gotcha.

What do you think of changing the behaviour of the `withX` and `setX` methods to also 'un-set' the other fields, so that the semantics match?

Happy to submit a PR if interested.

**Comment by mikepenz** [comment]
@danhawkes yeah that's true that it is a bit of a problem if you mix up both methods. a reset of the other value would be a good start. 

the trouble continues with the getter methods in the callback. the `getName` will just return a value of the drawerItem if you set it via string, and the `getNameRes` if you set it via resource. This is the case because i don't have access to the context at the moment of setting those values. the strings are then fetched during the item creation.
