### ISSUE TITLE
possible bug: DrawerLayout must be measured with MeasureSpec.EXACTLY when using ConstraintLayout

### ISSUE THREAD

**Issue by or-dvir** [mikepenz/MaterialDrawer#2342]
## About this issue
trying to put drawer under the toolbar as explained [here](https://github.com/mikepenz/MaterialDrawer/blob/develop/FAQ/howto_show_drawer_under_toolbar.md) and getting `DrawerLayout must be measured with MeasureSpec.EXACTLY` exception.

after some playing around with it i have noticed it's only happening if my XML root view is `ConstraintLayout`.
if i change it to `RelativeLayout`, it working fine.

**_NOT_** working (getting exception mentioned above):
```
<?xml version="1.0" encoding="utf-8"?>

<android.support.constraint.ConstraintLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.Toolbar
        <!--some values-->
     />

    <FrameLayout
        android:id="@+id/drawerContainer"
               <!--some values-->
     >

        <ScrollView
           <!--some values-->
     >
            <!--layout content-->

        </ScrollView>
    </FrameLayout>
</android.support.constraint.ConstraintLayout>
```

working:
```
<?xml version="1.0" encoding="utf-8"?>

<RelativeLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <android.support.v7.widget.Toolbar
        <!--some values-->
     />

    <FrameLayout
        android:id="@+id/drawerContainer"
               <!--some values-->
     >

        <ScrollView
           <!--some values-->
     >
            <!--layout content-->

        </ScrollView>
    </FrameLayout>
</RelativeLayout>
```

## Details
- [ ] Used library version **6.0.9**
- [ ] Used support library version **27.1.1**
- [ ] Used gradle build tools version **3.1.3**
- [ ] Used tooling / Android Studio version **3.1.3**
- [ ] Other used libraries, potential conflicting libraries **using the kotlin wrapper library**

**Comment by mikepenz** [comment]
@or-dvir not really sure the DrawerLayout which gets inflated is `MATCH_PARENT`, `MATCH_PARENT` so it should be absolutely fine

**Comment by or-dvir** [comment]
well... if its constraint layout it doesnt work

**Comment by mikepenz** [comment]
Did you figure this out already? or are there any new details?

**Comment by or-dvir** [comment]
@mikepenz no solution found. im just using relative layout...

**Comment by mikepenz** [comment]
Ok so this is a known thing of the `DrawerLayout` and the `ConstraintLayout` and many people complain about it...

https://stackoverflow.com/questions/42170694/how-to-suppress-constraint-layout-error-match-parent-is-not-supported-in-constr
https://stackoverflow.com/questions/47001482/drawerlayout-inside-constaintlayout-java-lang-illegalargumentexception-drawer

I was able though to figure out a configuration of the layout with the `ConstraintLayout` which works perfectly :) 

See this commit:
https://github.com/mikepenz/MaterialDrawer/blob/3878084e7a0e37631ac85694c3ccfb0cb85afff3/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml

And specifically these lines (super important those 0dp)
https://github.com/mikepenz/MaterialDrawer/blob/3878084e7a0e37631ac85694c3ccfb0cb85afff3/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml#L23-L28

using this will make it work perfectly fine ;)
the sample now also uses constraint layouts instead of relative layouts :D

**Comment by or-dvir** [comment]
thanks mike!

**Comment by atulbhardwaj0900** [comment]
> Ok so this is a known thing of the `DrawerLayout` and the `ConstraintLayout` and many people complain about it...
> 
> https://stackoverflow.com/questions/42170694/how-to-suppress-constraint-layout-error-match-parent-is-not-supported-in-constr
> https://stackoverflow.com/questions/47001482/drawerlayout-inside-constaintlayout-java-lang-illegalargumentexception-drawer
> 
> I was able though to figure out a configuration of the layout with the `ConstraintLayout` which works perfectly :)
> 
> See this commit:
> https://github.com/mikepenz/MaterialDrawer/blob/3878084e7a0e37631ac85694c3ccfb0cb85afff3/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml
> 
> And specifically these lines (super important those 0dp)
> https://github.com/mikepenz/MaterialDrawer/blob/3878084e7a0e37631ac85694c3ccfb0cb85afff3/app/src/main/res/layout/activity_sample_custom_container_dark_toolbar.xml#L23-L28
> 
> using this will make it work perfectly fine ;)
> the sample now also uses constraint layouts instead of relative layouts :D

This is working
