### ISSUE TITLE
Can't change statusbar color when statusbar is translucent

### ISSUE THREAD

**Issue by adeldolgov** [mikepenz/MaterialDrawer#2473]
Hello! 
I'm using com.mikepenz.materialize.view.ScrimInsetsRelativeLayout as parent in my activity.
Inside of it, i have SupportMapFragment.

I can't change statusbar color programmatically.
I tried : 
```
materialDrawer.getDrawerLayout().setStatusBarBackgroundColor(getResources().getColor(R.color.colorPrimaryDark));
materialDrawer.getMaterialize().setStatusBarColor(getResources().getColor(R.color.colorPrimaryDark));
```
Both of them didn't work.

**Comment by mikepenz** [comment]
Not 100% sure but I believe you can not change the statusBar color like this if it's translucent. (it doesn't come from the underlaying views in this case I think) 

have you checked to set the color via the theme, or the window?

**Comment by adeldolgov** [comment]
`getWindow().setStatusBarColor(ContextCompat.getColor(MainActivity.this, R.color.colorPrimaryDark));`
It works if we use window, but then navigtaion drawer header below statusbar color.

**Comment by kibotu** [comment]
i've had a similar issue which turned out to be 
```
DrawerBuilder()
  // .... 
  .withSystemUIHidden(true)
  .build()
  .also {
     if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
       it.drawerLayout.fitsSystemWindows = false // make sure to check all layouts have the intended setting for this flag
     }
  })
```

also relevant [setting translucent flags](https://github.com/exozet/AndroidCore/blob/master/core/src/main/java/com/exozet/android/core/extensions/Activity+Extensions.kt#L68-L80) programmatically: 

as well as configuring all [window/statusbar/navigationbar flags](https://gist.github.com/kibotu/31474ed3511836c243c7e61326d777ab) as desired (pick the ones you want)

**Comment by mikepenz** [comment]
@adeldolgov where you able to figure out the problem?

**Comment by mikepenz** [comment]
Please report back if this is still relevant
