### ISSUE TITLE
On Dynamic Switching Topics

### ISSUE THREAD

**Issue by wangliyang206** [mikepenz/MaterialDrawer#2488]
Recently, in switching between day mode and night mode (no need to restart Activity), Activity uses result. resetDrawerContent () and result. getDrawerLayout (). invalidate () after switching themes; both can't work very well. Do you have dynamic switching themes or better ways in Material Drawer?

**Comment by mikepenz** [comment]
most colors are attributes are resolved from the theme, and not really done dynamically. 

if you switch the theme I believe a activity recreation is common.

**Comment by wangliyang206** [comment]
Material Drawer puts a SwitchDrawer Item to switch existing black and white topics. Which interface can refresh View by calling after the switch?

**Comment by mikepenz** [comment]
As mentioned there is no dynamic theming support. if you have changed the design the normal activity recreation is suggested. 

Otherwise you could manually redesign all views, but that is not really suggested.


For example 
https://developer.android.com/reference/android/app/Activity.html#recreate()

**Comment by mikepenz** [comment]
In general most contents of the drawer are recyclerView items. so theoretically re-adding them (if the context is the right one might already solve your problem. 

the sticky footer might require removing and re-adding the items.
