### ISSUE TITLE
8.0.0 Design Doc

### ISSUE THREAD

**Issue by AllanWang** [mikepenz/MaterialDrawer#2535]
Is there any design doc or issue(s) we should be looking at for the 8.0.0 update? For instance, why is xml now introduced?

**Comment by mikepenz** [comment]
The main write-up I have done until to this point is in the alpha release notes. 

But I can definitely come up with a more structured document to point out the thoughts behind this major release.

In general to sum it up:

- remove "magic" functionality which is not really clear what is going on
  - e.g. automatically adjusting the layout hierarchy to inject the `DrawerLayout`
    - removing this brings great simplifications like no more (direct) handling for the ActionBarDrawerToggle, DrawerLayout, fitsSystemWindows behavior, ... 
- proper theme support
  - e.g. proper dark / light theme
  - colors should all be resolved from theme
- simplified dependencies 
  - eliminate materialize as the end goal
  - eliminate Android-Iconics as direct dependency (add ktx-extension for support)
- remove legacy code due to the above matters
- similar way of usage as the `NavigationView` itself
  - the view is added, and then the UI can be updated dynamically via relevant functions
  - eliminates builder code, and duplicated code

Some of the above functionality like auto inflation, or ActionBarDrawerToggle support might be added as extensions again. but the core should be as minimalistic as possible. 

Also as a further run I'd absolutely love to enhance the account header behavior.

**Comment by AllanWang** [comment]
Sorry for the late reply. Regarding theme support specifically, I believe attribute resolution is fair, but is there also anything stopping programmatic bindings? Are there situations where reflection or some non API was used in the past? I do have apps that allow for user generated themes, so it's probably in the minority, but that is dependent on fully programmatic views.

Even if that wasn't the case, people may appreciate passing a specific theme/style programmatically vs requiring an XML component.

I'd be able to help in this part if it's currently not on the roadmap but is still feasible

**Comment by mikepenz** [comment]
@AllanWang in general I'd love to streamline things more towards embracing the theme engine from the android system more and have id's on every element so you can practically change the colors. The items themself are customizable already. 

In general the question is how much overhead for dynamic theming it is worth to offer. especially as the general requirement is to recreate the activity for a different theme. 

I suppose the whole theming topic will only be improved as soon as compose will be available.

**Comment by mikepenz** [comment]
What I may think could be rather simple to implement, and super flexible. would be a way to intercept the resolve code for theme colors. (as long as they are set programmatically) 

so you would have some code like:

```kotlin
Drawer.setStyleInterceptor { attrId ->
    when (attrId) {
         R.attr.primaryColor -> Color.RED
         ....
    }
}
```

Not sure if this would already serve your requirements?

**Comment by AllanWang** [comment]
Not too sure how compose will affect this, but most views in general come with programmatic theme properties. As you mentioned, using the theme engine would be a matter of supporting ids, but adding programmatic support would just be a new method + color reference per attribute. If there are colors in MaterialDrawer's child views that can only be defined in xml, then that's a different story and it may make sense to drop programmatic support.

Style interceptor is interesting and would suit my needs, but I'm not sure if that's possible/optimal. I haven't seen any other library use something like that, and the notion of programmatic themes doesn't seem possible in Android.

**Comment by mikepenz** [comment]
Well compose will basically affect it in a fashion that this library will become obsolete :D and I hope the general plan will be to completely redo how theming works and will be a lot more flexible when it comes to programmatic usage. 

The idea would be a less verbose approach to intercepting changing colors programmatically. but on the other hand. most colors in the `Drawer` are anyways the items. the header itself is rather simple, and then there is the background. as such ensuring the items are gonna stay flexible enough shall be sufficient :) 

Perhaps it would help to go over the elements you use and see where we miss the potential to do programmatic theming?

**Comment by AllanWang** [comment]
Given that my theme generation is all programmatic, I would essentially need to control [all theme attributes](https://github.com/mikepenz/MaterialDrawer#custom-style---stylesxml). The bare minimum would probably be the text, background, and accents. Things like dividers are okay to remain grey for light and dark

**Comment by mikepenz** [comment]
Ok let's keep this in mind should be definitely doable :) 

Btw. Thank you so much for the sponsor!

**Comment by AllanWang** [comment]
Thanks. I'm actually rewriting my project to see if it's possible to avoid non-google UI dependencies (https://github.com/AllanWang/Frost-for-Facebook/pull/1601), so this isn't critical, but this would still be good to have for others. Given that you seem to have complete control over your UI, it should definitely be doable.

Note that my sponsorship if for all the help you've given to me and other throughout the years, and is not tied to this specific issue.

**Comment by mikepenz** [comment]
@AllanWang so all views should be accessible with ID and allow via this approach to modify their colors. 

for the `DrawerItems` accessing the items directly is not really possible. but due to the flexible API all items can be overwritten and adjusted to your needs. having additional setters for all possible color values seems to be overkill I believe, as for 99% of all usecases having the colors via the theme only should be enough. 

If there is something which you can not color / theme please let me know before we are gonna reach RC level :) 

and then everything is anyways obsolete as soon as composer can be used :D

**Comment by AllanWang** [comment]
I've since rewritten nav bar myself, and no longer use Material Drawer for that project. I do agree that complete customization is overkill, which is why I'm not pushing for it in this project. Anything I do in the future will likely not use that, as I would be pushing more for correctness rather than customization

**Comment by mikepenz** [comment]
Thank you so much for the details really appreciate it.
