### ISSUE TITLE
descripdescriptionTextColor not work for PrimaryDrawerItem in 8.0.0-b03

### ISSUE THREAD

**Issue by beeline09** [mikepenz/MaterialDrawer#2564]
I test two variants:
```kotlin
val itemSync = PrimaryDrawerItem().apply {
            name = StringHolder("Получение справочников")
            description = StringHolder("Посл.раз: $lastDateSync")
            descriptionTextColor = ColorHolder.fromColor(color_int)
            identifier = Constants.MATERIAL_DRAWER.ITEM_IDS.SYNC_GET_REFERENCES
            icon = ImageHolder(R.drawable.ic_sync_black_50dp)
        }
        
val itemSync = PrimaryDrawerItem().apply {
            name = StringHolder("Получение справочников")
            description = StringHolder("Посл.раз: $lastDateSync")
            descriptionTextColor = ColorHolder.fromColor(Color.RED)
            identifier = Constants.MATERIAL_DRAWER.ITEM_IDS.SYNC_GET_REFERENCES
            icon = ImageHolder(R.drawable.ic_sync_black_50dp)
        }
```
and i see that descriptionTextColor not working.
![Screenshot_1582792633](https://user-images.githubusercontent.com/2519627/75426567-ff632000-5955-11ea-88a3-9faab25012d7.png)

**Comment by mikepenz** [comment]
Thanks. You are right this was no longer forward ported with v8. I have fixed it by simplifying the api and enhancing it by allowing a `ColorStateList` instead of a single color. 

The preferred approach for coloring items would still be to define the colors via the theme as expected. You might want to look into this. 

Fix published in v8.0.0-b04
