### ISSUE TITLE
No ripple effect on drawer items

### ISSUE THREAD

**Issue by connyduck** [mikepenz/MaterialDrawer#2584]
## About this issue

There is no more ripple effect when touching a drawer item in MaterialDrawer 8, like there was in 6.1.2.
To reproduce, check the sample app, it also does not have the ripple effect.
As far as I can tell, `ProfileSettingDrawerItem` is an exception, as it does have the ripple background.

## Details
- Used library version 8.0.1 / current develop

**Comment by mikepenz** [comment]
@connyduck you may use the wrong theme. 

I just looked into the demo app and it is there.

**Comment by connyduck** [comment]
Ok, I just double checked and it seems to affect only Android 5 (and possibly lower?)

**Comment by mikepenz** [comment]
Yeah. Ripples are anyways only super smooth on newer versions and on old versions we do compat mode without them.

**Comment by connyduck** [comment]
Ok, fine with me. But why does the `ProfileSettingDrawerItem` have a ripple effect on Android 5 then 🤔

**Comment by Kashish-Sharma** [comment]
@mikepenz Also primary drawer items (text and icon) aren't getting disabled tint when `enabled=false`.
Do we have to implement something custom here ?

**Comment by mikepenz** [comment]
@connyduck because it does not implement the selected state like normal drawer items according to the material guidelines v2. it simply uses a selectable background:

https://github.com/mikepenz/MaterialDrawer/blob/develop/library/src/main/java/com/mikepenz/materialdrawer/model/ProfileSettingDrawerItem.kt#L72

vs. the main drawer items doing this:

https://github.com/mikepenz/MaterialDrawer/blob/25f73e431e6b77a91780e8a408baddf7ce7c6a1b/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt
See this particular code: https://github.com/mikepenz/MaterialDrawer/blob/25f73e431e6b77a91780e8a408baddf7ce7c6a1b/library/src/main/java/com/mikepenz/materialdrawer/util/DrawerUtils.kt#L376-L390

We did decide not to use ripple drawables backward here as it was causing issues. 

If you find a great way to make it work with insets and states I'd highly appreciate it
