### ISSUE TITLE
How to disable hamburger/arrow animation?

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#26]

**Comment by mikepenz** [comment]
@Rainer-Lang you want the drawerToggle without animation? Not sure if this is possible.

Just use the lib without the useActionBarDrawerToggle and handle the open and closeDrawer on your own ;). 

You have to define your own drawable in the ActionBar/Toolbar and implement it as you would without the ActionBarDrawerToggle

**Comment by intrications** [comment]
Shouldn't this line already be disabling the animation?

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/res/values/styles.xml#L66

Although maybe I'm misunderstanding the "spinbars" attribute.
```<!-- Whether bars should rotate or not during transition -->
    <attr name="spinBars" format="boolean"/>```

**Comment by mikepenz** [comment]
@intrications as far as i can tell the AnimationDrawerToggle is meant to be animated. I would give you the advice to do it custom and open and close the drawer on its own.

**Comment by intrications** [comment]
@mikepenz 

I don't think it is meant to be animated because it will immediately be covered by the Navigation Drawer. What's the point of changing to a back arrow that can't be seen or pressed?

But the Google Apps do it both ways so I don't know what the official answer is. Gmail doesn't animate, YouTube does.

You can hardly see the animation anyway so I'm not going to worry too much.
