### ISSUE TITLE
Can you provide some demos of usage for MD with JAVA?

### ISSUE THREAD

**Issue by essencer** [mikepenz/MaterialDrawer#2648]
## About this issue
- I know almost nothing about KT and I want to use MD of the latest version.
- How to add PrimaryDrawerItem or SecondaryDrawerItem and set listener for them in MD(8.1.5) with JAVA.
- Can you provide some demos of usage for MD with JAVA?

Thank you very much!

**Comment by mikepenz** [comment]
We sadly faced out Java support altogether in favor of simpler code and less to maintain. 

There are no plans to offer full Java support anymore nor create samples. 

It should be possible to do many things in Java but some won't. I'd suggest to have the code using the drawer in kotlin. Allowing you to slowly migrate the rest of your app.

Otherwise please stick with v6 which is given as is. No more updates are planned for it though.

**Comment by mikepenz** [comment]
I hope you understand.

**Comment by essencer** [comment]
> I hope you understand.

Have done in KT. Thanks.

**Comment by mikepenz** [comment]
Small disclaimer. When you start to love kotlin you won't ever go back to Java :D
