### ISSUE TITLE
Can I use Java?

### ISSUE THREAD

**Issue by ranzeng** [mikepenz/MaterialDrawer#2650]

**Comment by mikepenz** [comment]
You will have trouble to get the latest version running with java. The library is in kotlin so its API will be best with Kotlin. 

You could use the library via kotlin and have a wrapper class which you then use from java. 

Note that I highly recommend to get started with Kotlin as it's the future :) and there's no reason to not jump into it now. 

otherwise you can use one of the old versions (which will get no more support)

**Comment by neroux** [comment]
Kotlin is 100% based on Java and all the generated code will be Java code, so there shouldn't be any issue using it.

Of course, because Java requires you to be more specific in what you want (which is hidden away by Kotlin) and because the library was not written with Java in mind, it might be a tad cumbersome to set up things.

```java
ModelAdapter<IDrawerItem<?>, IDrawerItem<?>> model = drawer.getItemAdapter();

PrimaryDrawerItem i = new PrimaryDrawerItem();
i.setName(new StringHolder("Title"));

model.add(i);
```

If you want to use it on Java you'll be probably happier by going with https://github.com/zirouan/NavigationDrawer-MaterialDesign for example.

**Comment by comradewalker** [comment]
@ranzeng  Here you are an simple example of java usage, not sure if everything works ok, but it builds and runs. But as @mikepenz  said, use kotlin, as it's future.

https://github.com/comradewalker/MaterialDrawer/blob/JavaExample/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivityJava.java
