### ISSUE TITLE
Question: min SDK

### ISSUE THREAD

**Issue by comradewalker** [mikepenz/MaterialDrawer#2667]
Is there any other reason for not being 14 besides this one:

Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 16 declared in library [com.mikepenz:aboutlibraries:8.4.2]

Libs build with minSdk 14, but app needs 16 because of dependency. Shouldn't libs then be 14 if no other reason? Tnx in advance

**Comment by mikepenz** [comment]
@comradewalker there are other changes we could do thanks to upgrading to API 16 in resources and other areas. 

Additionally I simply can't support 14 anymore, as I don't own any phone with that API level anymore, and based on usage numbers (and https://twitter.com/minSdkVersion) you should actually consider to be 23+ 

(personally I'd say 24+ is more favorable, due to significant improvements in the SDK)

If you really need to support 14+ for some reason, please consider staying with older releases of the library still supporting such lower sdk versions (there won't be support from our side for problems with API 14 in either way though)

**Comment by comradewalker** [comment]
Well, that was fast. Tnx
