### ISSUE TITLE
FileNotFoundException: res/drawable-xhdpi-v4/abc_text_cursor_mtrl_alpha.9.png

### ISSUE THREAD

**Issue by sdeff** [mikepenz/MaterialDrawer#292]
Hi,

I just uploaded a new app update including MaterialDrawer.

It crashed the following device:
![bildschirmfoto 2015-05-07 um 18 37 12](https://cloud.githubusercontent.com/assets/2885756/7520604/1fad4322-f4e8-11e4-8f34-3ae6e95c16ca.png)

With a NotFoundException:
http://pastebin.com/nVJtYyR2

Is there anything I can do about it?

**Comment by mikepenz** [comment]
@sdeff for sure. but as far as i can tell from the log it's nothing caused by the MaterialDrawer. The online line which contains the materialdrawer package is this one:
com.mikepenz.materialdrawer.view.ScrimInsetsFrameLayout.draw(SourceFile:85)

but this is not the issue here. As far as i can tell you have done something with tinting the widgets and somewhere a drawable which is missing. (just to prove that this is no issue by the MaterialDrawer, it only includes one single drawable and this is: circle_mask.xml)
