### ISSUE TITLE
Profile Image not showing up in the AccountsHeader

### ISSUE THREAD

**Issue by patnisonal** [mikepenz/MaterialDrawer#297]
I am trying to show the Google Plus picture of the user in the Accounts Header. Here is the code written to achieve this.

Uri dpUri = Uri.parse(url); // some valid URL for fetch Google Plus Profile Picture.
headerResult.addProfiles(new ProfileDrawerItem().withName(name).withEmail(accountName).withIcon(dpUri));

This doesn't show the profile picture in the Account Header. Am I missing a step here?

**Comment by abuzuhri** [comment]
I have same problem

**Comment by mikepenz** [comment]
@patnisonal @abuzuhri as shown in the sample application your app must init the DrawerImageLoader. As this library does not contain an ImageLoading library (because everyone uses different ones, Picasso, Glice, ...) 

A detailed instruction is shown here:
https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomApplication.java#L22

This should be done before loading the first image (i prefer the implementation in the Application)
```java
        //initialize and create the image loader logic
        DrawerImageLoader.init(new DrawerImageLoader.IDrawerImageLoader() {
            @Override
            public void set(ImageView imageView, Uri uri, Drawable placeholder) {
                Picasso.with(imageView.getContext()).load(uri).placeholder(placeholder).into(imageView);
            }

            @Override
            public void cancel(ImageView imageView) {
                Picasso.with(imageView.getContext()).cancelRequest(imageView);
            }

            @Override
            public Drawable placeholder(Context ctx) {
                return null;
            }
        });
```

**Comment by patnisonal** [comment]
Thanks! Just tried your suggestion. This has started to work for me perfectly.

rgds
