### ISSUE TITLE
Animate drawer items at opening

### ISSUE THREAD

**Issue by MassiveZergInc** [mikepenz/MaterialDrawer#324]
Hello,

my question is if its possible to implement a drawer items animation, when the drawer is opened.

attachment:

https://d13yacurqjgara.cloudfront.net/users/396127/screenshots/2044462/hg_animation.gif

**Comment by mikepenz** [comment]
@MassiveZergInc theoretically it is possible to animate the ListView items. As of the Material Design Guidelines this is not specified. If you really need this look for animating ListView items. You can get the reference to the ListView from the Result object. 

As of animating the switch of the normal drawer item list to the account list. This is not possible because the header or footer is also part of the ListView (footerView, headerView) and so they will also animate. 

I hope this helps
