### ISSUE TITLE
Ripple is not displayed for StickyDrawerItems

### ISSUE THREAD

**Issue by RubenGees** [mikepenz/MaterialDrawer#357]
Items can be selected but they don't play the ripple Animation. The normal section works fine.
Library: 3.0.2 OS: 5.1

**Comment by mikepenz** [comment]
@RubenGees i have a nexus 5 with Android 5.1 and i see the ripple. 

![screenshot_2015-05-26-18-14-29](https://cloud.githubusercontent.com/assets/1476232/7817158/37940896-03d3-11e5-9c36-f7df95577250.png)

**Comment by RubenGees** [comment]
I'll make a Video later. My Device is nexus 6

**Comment by mikepenz** [comment]
@RubenGees ah i have found what you mean. with a touch

**Comment by RubenGees** [comment]
Okay, great

**Comment by mikepenz** [comment]
@RubenGees ok the ripple is working as it should but only if this item is not checkable. this makes sense because the drawable is replaced as soon as your select it. so if you want the ripple to play. this item should not switch in a selected state afterwards.

**Comment by RubenGees** [comment]
I'm not sure if I understand what you want to say. Why shouln't the ripple play if the user selects the item? I thought a ripple shows, that the user pressed something?
And why is it working then in the normal Section? (Above the StickyBottom one)

I'm sorry if you make an obvious point and I just don't get it :D

**Comment by mikepenz** [comment]
@RubenGees it is "working" there because it has another layer. i really suggest that this stays just for the list, because i do not want to add another layout layer to the footer. the list draws the selector on top of the item. and the selected image is in the background. this is not the case for the footer. 

the user will directly see that he has selected something as the icon get's the selected state. if you have an issue with this you can also set the drawerClose delay to 0. this will be a bit sluggish in some cases if you switch fragments, but the user won't actually see that the ripple would have been showed.

**Comment by RubenGees** [comment]
Okay thank you for the clarification! I'm a bit of a perfectionist so I noticed that, but it's perfectly okay if you don't want to change that. Thank you for your work!

**Comment by mikepenz** [comment]
@RubenGees i'm also an perfectionist. but in this case performance is a bit more important ;)

thanks for all your input. i do my best to keep it perfect :P
