### ISSUE TITLE
Question: Using .withTag(Object object) properly?

### ISSUE THREAD

**Issue by Anatidae-Project** [mikepenz/MaterialDrawer#361]
I didn't want to maintain a separate array along side my drawer items. So I just shoved my fragments into the .withTag method. When a drawer is clicked on, I use getTag to grab the fragment and replace it in the view. 

I also use getTag to compare if the current fragment is part of the menu structure on my OnBackackStackChangedListener. I compare what fragment is in the backstack and if it matches a menu item with a matching fragment in getTag, I put back the burger icon from whatever it was before. 

With your new update, you mention updating the setTag. And I am thinking that perhaps throwing references in there might be a bad idea for my future.

Thoughts? Recommendations?

**Comment by mikepenz** [comment]
@Anatidae-Project i was referring to the following commit:
https://github.com/mikepenz/MaterialDrawer/commit/45926c8147aa1cbf35fa56b8bf4238db452d9572

I use the `setTag()` method and `getTag()` methods for the header to get the reference of the profile set in the circle images on the top. as these are ImageViews and users have the option to provide any image loading library on their own the imageViews are used directly. With Picasso it does not make any problems, but if you choose to use Glide it will break if a tag was set on an ImageView. It is just because of their implementation and i did not know about any other library doing the same. (in fact glide does no work yet because somehow it runs into a circular operation....) 

you should be save doing so. (as long as you don't set the tag on an ImageView in combination with Glide ;)
