### ISSUE TITLE
withDisplayBelowToolbar(true); - toolbar items not clickable.

### ISSUE THREAD

**Issue by Aeefire** [mikepenz/MaterialDrawer#430]
I implemented a drawer with Gravity.RIGHT with "withDisplayBelowToolbar(true);" in order to keep it below the toolbar (just like the notification drawer in Google+). 

However, the toolbar items are not clickable anymore when the drawer is open. It causes the drawer to close though.

if you need any further explanations, just ask.

edit: similiar to the slidinglayer from the right, as seen in this video: https://www.youtube.com/watch?v=162oD0XPM40

**Comment by mikepenz** [comment]
@Aeefire yeah because if you use the default implementation the drawer is FULLSCREEN .This can't be changed. If you want the drawer to be only below the toolbar you will have to look at the `CustomContainerActivity` https://github.com/mikepenz/MaterialDrawer/blob/master/app/src/main/java/com/mikepenz/materialdrawer/app/CustomContainerActivity.java

**Comment by mikepenz** [comment]
@Aeefire if you have a left and a right drawer you will have to create a normal Drawer. And then another CustomContainerActivity. Those are more complex things and require a bit more work on your side.

**Comment by Aeefire** [comment]
@mikepenz thanks. This did the job. Amazing support.
