### ISSUE TITLE
DrawerBuilder.

### ISSUE THREAD

**Issue by Grozny** [mikepenz/MaterialDrawer#433]
How can i cnange profile without close the drawer?

**Comment by mikepenz** [comment]
@Grozny when you switch the profile through which method? 
It is possible for the header, and the small profile icons. But not though the profiles in the list. This is caused by the following:

https://github.com/mikepenz/MaterialDrawer/blob/master/library/src/main/java/com/mikepenz/materialdrawer/accountswitcher/AccountHeaderBuilder.java#L1185

Because i have to reset the drawer through a handler to keep it smooth, but i will have to return the state if the event was consumed directly.

**Comment by Grozny** [comment]
With withOnAccountHeaderListener method.

2015-06-18 18:38 GMT+01:00 Mike Penz <notifications@github.com>:

**Comment by mikepenz** [comment]
@Grozny with the OnAccountHeaderListener you can just pass `true` which states that the event was consumed, and nothing else will happen.
