### ISSUE TITLE
setDisplayHomeAsUpEnabled(true) goes nowhere

### ISSUE THREAD

**Issue by vishnudbimcs** [mikepenz/MaterialDrawer#50]
I've called setDisplayHomeAsUpEnabled(true) and the arrow is showing, but it goes no where.

How can I do this

thanks.

**Comment by vishnudbimcs** [comment]
I achieved the same by adding the following line in Manifest file
 <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity" />

Please suggest me if there is another way to do so.

**Comment by mikepenz** [comment]
@vishnudbimcs you mean the drawer toggle? the library itself provided basic drawer toggle functionality. you can also get the object back from the result. 

This library handles the MaterialDrawer and just basic stuff around it. So for special cases with the Toolbar or the ActionBarToggler just implement it as you would if you create a normal application. ;)

**Comment by gpulido** [comment]
Hello In ma use case I have an activity A with the Drawer and inside it I inflate a fragment A.
The drawer has .withActionBarDrawerToggle(true) and I haven't set the getSupportActionBar().setDisplayHomeAsUpEnabled(true);
Then, inside the Activity A y replace the fragment A by the fragment B, and I want to show the "backbutton"  instead of the drawer toggle, after inflating the fragment B I do:
```Java
result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
 getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```
And the backbutton is showed, however if I press it it doesn't do anything. I have also made the Activity Override the OnbackPressed: 
```Java
 @Override
  public void onBackPressed() {
}
```
But it is never hit.
I also have added onOptionsItemselected, but again nothing happens.

So I tested more things.
1) I removed the Drawer, and just use the  
```Java
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```
Results: Back button on Fragment A and B and it works.

2) Using the drawer, but NOT changing the result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);
when loading Fragment B
Result: The Hamburguer icon on Fragment A and B

3) Setting getSupportActionBar().setDisplayHomeAsUpEnabled(true); at the init of the Application,
and result.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false); when loading the Fragment B
Result: hamburguer on Fragment A, nothing show on Fragment B

I don't know what is happening here...

**Comment by mikepenz** [comment]
@gpulido please read the following regarding this behavior

https://github.com/mikepenz/MaterialDrawer/issues/65

Thanks

**Comment by lexrobinson** [comment]
First you need to initialize the toolbar :
--------------------------------------------
Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
setSupportActionBar(toolbar);
-------------
then call the back button from actionBar :
-------------
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
getSupportActionBar().setDisplayShowHomeEnabled(true);
------------------------------------
@Override
public boolean onSupportNavigateUp() {
    onBackPressed();
    return true;
}
