### ISSUE TITLE
Style paramaters seemingly unrelated to the drawer in the library

### ISSUE THREAD

**Issue by fdorssers** [mikepenz/MaterialDrawer#61]
During implementation of your drawer into an application I noticed that it also changes quite a few style parameters which seemingly have nothing to do with the drawer. For example I noticed that my cards are hardly visible with the white background that for example `MaterialDrawerBaseTheme.Light` gives as `android:windowBackground`:
```XML
<item name="colorPrimary">@color/material_drawer_primary</item>
<item name="colorPrimaryDark">@color/material_drawer_primary_dark</item>
<item name="colorAccent">@color/material_drawer_accent</item>

<item name="android:windowBackground">@color/material_drawer_window_background</item>
```
Obviously one can simply extend `MaterialDrawerBaseTheme.Light` and change these again, or override the colors as you mention on the github homepage under the section 'styles.xml (OPTIONAL)', but I was wondering if there is anything specific that these are used for in the library. 

Other than that it was really easy to implement. I especially like that I don't need to override a special activity that comes with the library like many others have.

**Comment by mikepenz** [comment]
@fdorssers in fact the only value i set which probably would not have to be set is the android:windowBackground. i'll try if everything works without this. 

defining the colorPrimary, colorPrimaryDark, colorAccent should cause no issues. and is also recommended if you use my theme because those will define your applicationColor. 
As a small extra the colors can also be changed by defining primary, primaryDark, accent without the prefix.


With the next update colors are also defined by style so if you use a dark style you will automatically get the dark drawer.

**Comment by fdorssers** [comment]
Thank you for taking your time to explain this :) .

**Comment by mikepenz** [comment]
@fdorssers no problem. if you have more questions just ask
