### ISSUE TITLE
Methods to set DrawerToggle (hamburger/back arrow)

### ISSUE THREAD

**Issue by Rainer-Lang** [mikepenz/MaterialDrawer#65]
I suggest to add methods to set the DrawerToggle to hamburger or back arrow.
So it would be possible to set this in activities and fragments very easy.
Is this ok Mike? ;-)

**Comment by mikepenz** [comment]
@Rainer-Lang thanks for the report but this should be handled by the dev itself.

Here i have a detailed answer for this decision:

If you want the back arrow you just have to set the following in your application
```java
getSupportActionBar().setDisplayHomeAsUpEnabled(true);
```
This will work for an ActionBar or Toolbar. 

So now there is one thing. This won't show the back arrow if we use an ActionBarDrawerToggle because this overwrites this behavior. So we have to disable this for our drawer by setting the following
```java
.withActionBarDrawerToggle(false)
```
For the functionality to go back you need the default implementation like this:
```java
@Override
    public boolean onOptionsItemSelected(MenuItem item) {
        switch (item.getItemId()) {
            case android.R.id.home:
                onBackPressed();
                return true;

            default:
                return super.onOptionsItemSelected(item);
        }
    }
```

Deciding if i want the ActionBarDrawerToggle or the BackArrow? 
Yeah it is a really simple decision because the Material Design Guidelines (or some other google android guidelines :D) state that a Drawer is just for the Main (the first) activity within your application. 


So one more thing. The Drawer itself overlaps the toolbar so it will also overlap the ActionBarDrawerToggle so it won't show the arrow. So why do we have the ActionBarDrawerToggle in this case. Because it's easier for me to implement the callbacks for the Hamburger click. And for the really rare usecase that someone does not have a fullscreen (full-height) drawer which will show the ActionBarDrawerToggle (and if this dev also enables the animation)

**Comment by achuinard** [comment]
When I use the code you suggested, your library is still intercepting the click of the back arrow (closing and opening the drawer). I'd like to pop the fragment stack on back click, which I thought your onBackPressed would do, but again the onOptionsItemSelected listener is not being triggered.

**Comment by raghunandankavi2010** [comment]
@mikepenz  **Yeah it is a really simple decision because the Material Design Guidelines (or some other google android guidelines :D) state that a Drawer is just for the Main (the first) activity within your application.**

The io schedule app  has a baseactivity and all other activities extending from it. The drawer their for all top level activities. 

So should the drawer be their for all activities? (confirming on the material specs)??

**Comment by mikepenz** [comment]
@raghunandankavi2010 i assume it should only be for the top level activity. if it is necessary to have different functionalities or views in the top level i would also give the advice to implement those via fragments and navigate through those fragments with the drawer. 

no jumping because we start a new activity. no complicate back stack or anything else. 

all sub functionality then can be an activity again but those don't require a drawer.

**Comment by mikepenz** [comment]
@achuinard as long as you provide a toolbar to the drawer it will handle it for you. you can overwrite the drawerListener and then consume those events if you like. or you don't pass an toolbar to it. or disable the drawerToggle

**Comment by FabianTerhorst** [comment]
How can i set ```setDisplayHomeAsUpEnabled``` when toolbar is set to the drawer after Initialisation with ```mDrawer.setToolbar(this, toolbar, true);``` When i set  after this ```mDrawer.getActionBarDrawerToggle().setDrawerIndicatorEnabled(false);``` and 
```ActionBar actionBar = getSupportActionBar();
            if (actionBar != null) {
                actionBar.setDisplayHomeAsUpEnabled(true);
                actionBar.setHomeButtonEnabled(true);
            }```
the drawer indicator is away but there is no other icon too.

**Comment by mikepenz** [comment]
@FabianTerhorst if you keep the default behavior you can change between arrow and normal hamburger icon with https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/AdvancedActivity.java#L174

**Comment by FabianTerhorst** [comment]
@mikepenz mDrawer.getActionBarDrawerToggle().setHomeAsUpIndicator(new IconicsDrawable(this, CommunityMaterial.Icon.cmd_arrow_left).color(Color.WHITE).sizeDp(IconicsDrawable.ANDROID_ACTIONBAR_ICON_SIZE_DP)); works too

**Comment by mikepenz** [comment]
@FabianTerhorst cool :D thanks

**Comment by FabianTerhorst** [comment]
@mikepenz from the docs "Resource ID of a drawable to use for the up indicator, or 0 to use the theme's default" .setHomeAsUpIndicator(0) but ActionBarDrawerToggle.getThemeUpIndicator() method return null too.

**Comment by mikepenz** [comment]
@FabianTerhorst to be fair i really don't know. i keep default behavior in my apps as far as possible.

**Comment by emersonjones** [comment]
Main -> fragment -> fragment (the last fragment) does not see the drawer to use ActionBarDrawerToggle, any suggestions?

**Comment by mikepenz** [comment]
@emersonjones your `Drawer` should be in the `Activity` and then your fragments just open / close the drawer of the activity

**Comment by emersonjones** [comment]
Thanks for the tip, I put the drawer as a public, and solved it.

**Comment by ChaosPower** [comment]
Hi @mikepenz ,

referencing issue posted on the kotlin version.

https://github.com/zsmb13/MaterialDrawerKt/issues/67

I am using crossfader and would like to toggle the drawer layout. Currently puzzled on how to do this.

**Comment by ChaosPower** [comment]
@mikepenz ,

I was able to solve my issue.

below is what I did. However, a bit hacky on forcing the hamburger icon to show up.

```java
private fun initDrawer(savedInstanceState: Bundle?) {

    supportActionBar!!.setHomeAsUpIndicator(R.drawable.ic_action_menu) // Hacky the vampire coder
    supportActionBar!!.setDisplayHomeAsUpEnabled(true) // Hacky the vampire coder

    resultDrawer = drawer {
        savedInstance = savedInstanceState

        toolbar = this@MainActivity.toolbar
        translucentStatusBar = false

        buildViewOnly = true
        generateMiniDrawer = true

        showOnFirstLaunch = true

        headerResult = accountHeader {
            selectionListEnabledForSingleProfile = false

            savedInstance = savedInstanceState
            translucentStatusBar = false
            background = R.drawable.header_bg

            mProfile = profile(App.prefs.firstName + " " + App.prefs.lastName, App.prefs.authEmail) {
                iconUri = Helper.drawableToUri(this@MainActivity, R.mipmap.ic_launcher_circle)
            }

            profileSetting("Logout") {
                iicon = GoogleMaterial.Icon.gmd_exit_to_app
                onClick { _ ->
                    logout()
                    false
                }
            }
        }

        sectionHeader("Available Tools")

        ToolsDataService.tools.forEach {
            primaryItem(it.name) {
                icon = it.menuResource
                onClick { _ ->
                    openTool(it)
                    true
                }
            }
        }

        divider()

        actionBarDrawerToggleAnimated = true
        actionBarDrawerToggleEnabled = true
    }

    val miniResult = resultDrawer.miniDrawer
    val firstWidth = UIUtils.convertDpToPixel(300f, this).toInt()
    val secondWidth = UIUtils.convertDpToPixel(72f, this).toInt()

    if (!::crossFader.isInitialized) {
        crossFader = Crossfader()
    }

    crossFader.withContent(cross_fader)
            .withFirst(resultDrawer.slider, firstWidth)
            .withSecond(miniResult.build(this), secondWidth)
            .withSavedInstance(savedInstanceState)
            .build()

    miniResult.withCrossFader(CrossfadeWrapper(crossFader))

    crossFader.crossFadeSlidingPaneLayout.setShadowResourceLeft(R.drawable.material_drawer_shadow_left)
}


override fun onCreateOptionsMenu(menu: Menu): Boolean {
    menuInflater.inflate(R.menu.activity_main_menu, menu)
    return true
}

override fun onOptionsItemSelected(item: MenuItem): Boolean {

    when (item.itemId) {
        android.R.id.home -> {
            crossFader.crossFade()
            return true
        }
    }

    return super.onOptionsItemSelected(item)
}
```
