### ISSUE TITLE
Sliding feature

### ISSUE THREAD

**Issue by davideas** [mikepenz/MaterialDrawer#767]
Hi Mike, you that know better your library, is it possible to add a sliding behavior to the drawer and main layout?

**Comment by mikepenz** [comment]
@davideas you description does not really state what you want to achieve. 

The drawer is a normal `DrawerLayout` so everything which can be done with a `Drawer` can be achieved. 

Otherwise there are other patterns possible like the `PersistentDrawer`  or the `MiniDrawer` or the `CrossfadeDrawer` but you can check out all of them via the sample app

**Comment by davideas** [comment]
Yes, maybe I can manage it with `PersistentDrawer`, it is closer of what I want. I will play more with that, but I think i cannot put it on the right since it's an extension of SlidingPane.
Probably, I will ask more question in the near future. Maybe you can keep this thread opened.
Thank you Mike for the support!

**Comment by mikepenz** [comment]
@davideas the Crossfader which is used is able to be used in RTL mode too. 

I will close it for now but you can reopen or continue with the discussion all the time and i will answer ;)
