### ISSUE TITLE
Icons colored incorrectly in AccountSection

### ISSUE THREAD

**Issue by rubengees** [mikepenz/MaterialDrawer#814]
I hava 2 entirely black icons. One for the normal drawer. The other one for the account section.
I set the icons like the following:

```java
new PrimaryDrawerItem().withIcon(R.drawable.ic_newspaper) //Drawer
```

```java
new ProfileSettingDrawerItem().withIcon(R.drawable.ic_logout) //Acount
```

The first one is colored correctly in some gray tone. The second one remains black, which looks weird.

Screenshots:

![news](https://cloud.githubusercontent.com/assets/8021265/11155211/82715fba-8a44-11e5-861f-2bc9fc355e9f.png) ![logout](https://cloud.githubusercontent.com/assets/8021265/11155210/82561b74-8a44-11e5-8665-dbf5b7ff9b3a.png)

**Comment by mikepenz** [comment]
@rubengees not sure if those two icons are different (their color) but have you enabled the icon tinting?

**Comment by rubengees** [comment]
The icons on the screenshots, are the icons as they are displayed in the App. They differ in color (might not be clear through the screenshots)
Tinting is enabled for the one thats added to the normal drawer, for the other one (Account) I have set nothing else than the title.

**Comment by rubengees** [comment]
Okay, got it, I had to enable `withiconTinted()`. What me has confused was, that I don't have to set that if I use one of the Icons integrated in Iconics...

**Comment by mikepenz** [comment]
@rubengees the iconics icon do not require this as the drawables are generated via an icon font. so no real image is lying around in your source (flexible, scaleable, ...) And they are also simply colored with the correct colors as defined in the `Material Design Guidelines` if you now use drawables i use the drawable color as default because that's the thing most people want to. I also do not know if they are already in the correct color. Even if tinting is fast it has a small performance impact (probably not noticeable) so it makes no sense to do this if the icons are already fine ;)
