### ISSUE TITLE
Collapsable items/section

### ISSUE THREAD

**Issue by somghosh** [mikepenz/MaterialDrawer#828]
Is there a way to achieve a collapsable section like:

Main Item 1
Main Item 2
Main Item 3 (has an arrow)
++ Sub Item 1 (hidden till Main Item 3 is clicked)
++ Sub Item 2  (hidden till Main Item 3 is clicked)

**Comment by mikepenz** [comment]
@somghosh not by default, but it's easy to add. 

I have added something like this to the sample app: 
https://github.com/mikepenz/MaterialDrawer/blob/develop/app/src/main/java/com/mikepenz/materialdrawer/app/DrawerActivity.java#L186
https://github.com/mikepenz/MaterialDrawer/commit/830e72733f75f620fbd6efe5cb24821fbe774b6f

For the arrow just create a customDrawerItem which has an arrow instead of the badge on the right.
