### ISSUE TITLE
DrawerBuilder.buildView ignores toolbar

### ISSUE THREAD

**Issue by mahendranv** [mikepenz/MaterialDrawer#880]
I have to use Mini Drawer in my application. Since DrawerBuilder.buildView ignoring the toolbar the actionbar toggle not working properly. It's fine with DrawerBuilder.build().

or 

Any other way drawer toggle (animated) and mini drawer can co-exist?

**Comment by mikepenz** [comment]
@mahendranv in a normal setup the `.build()` will only handle the `ActionBarDrawerToggle` for you. You have to handle this on your own, because an `ActionBarDrawerToggle` requires a `DrawerLayout` but the implementation with the `MiniDrawer` to normal `Drawer` doesn't use a `DrawerLayout` 

There are libs out which provide a custom implementation to allow a custom `NavigationIcon` in the toolbar, with listeners, and animation.
