### ISSUE TITLE
can you add fragment item support?

### ISSUE THREAD

**Issue by jiqimaogou** [mikepenz/MaterialDrawer#97]
```
        new PrimaryDrawerItem().withName(R.string.drawer_item_home).withFragment(ListFragment.class),
```

**Comment by mikepenz** [comment]
@jiqimaogou what do you mean? 

The drawer does not manage it's content view. This is up to you.

You can use the listener methods to get notified as soon as he clicked on a list entry. Then just do your own logic displaying the fragment.

**Comment by jiqimaogou** [comment]
I think it is a common function in drawer layout, and it make the drawer easy to use.

**Comment by mikepenz** [comment]
@jiqimaogou what should be the outcome of this function. You pass the class and get the class in the onDrawerItemClickListener?

**Comment by jiqimaogou** [comment]
sorry for my english. I means add support fragment navigation. I think fragment navigation in drawer is very common. like https://github.com/neokree/MaterialNavigationDrawer.

**Comment by mikepenz** [comment]
@jiqimaogou as far as i can see the linked drawer requires you to use fragments. 

This library creates the drawer for you. It's up to you how to handle and what to do with an onClick on a specific item. 

Just implement the onDrawerItemClickListener and show the fragment. You can also process something there, or anything. 

I think it makes more sense that the developer implements this part because he can do everything then. Not as it's done with the other library which forces you to use fragments or similar.
